// Generated by `wit-bindgen` 0.50.0. DO NOT EDIT!
//
// This code was generated from the following packages:
//     fermyon:spin
//     wasi:io@0.2.0
//     wasi:clocks@0.2.0
//     wasi:random@0.2.0
//     wasi:filesystem@0.2.0
//     wasi:sockets@0.2.0
//     wasi:cli@0.2.0
//     wasi:http@0.2.0
//     wasi:io@0.2.0-rc-2023-10-18
//     wasi:clocks@0.2.0-rc-2023-10-18
//     wasi:random@0.2.0-rc-2023-10-18
//     wasi:filesystem@0.2.0-rc-2023-10-18
//     wasi:sockets@0.2.0-rc-2023-10-18
//     wasi:cli@0.2.0-rc-2023-10-18
//     wasi:http@0.2.0-rc-2023-10-18
//     fermyon:spin@2.0.0
//     wasi:keyvalue@0.2.0-draft2
//     spin:postgres@3.0.0
//     wasi:config@0.2.0-draft-2024-09-27
//     fermyon:spin@3.0.0
//     spin:postgres@4.0.0
//     spin:sqlite@3.0.0
//     wasi:io@0.2.3
//     wasi:clocks@0.2.3
//     wasi:filesystem@0.2.3
//     wasi:sockets@0.2.3
//     wasi:random@0.2.3
//     wasi:cli@0.2.3
//     wasi:http@0.2.3
//     spin:up@3.2.0
//     spin:up@3.4.0
//     wasi:clocks@0.3.0-rc-2025-09-16
//     wasi:random@0.3.0-rc-2025-09-16
//     wasi:filesystem@0.3.0-rc-2025-09-16
//     wasi:sockets@0.3.0-rc-2025-09-16
//     wasi:cli@0.3.0-rc-2025-09-16
//     wasi:http@0.3.0-rc-2025-09-16
//     wasi:io@0.2.6
//     wasi:clocks@0.2.6
//     wasi:filesystem@0.2.6
//     wasi:sockets@0.2.6
//     wasi:random@0.2.6
//     wasi:cli@0.2.6
//     wasi:http@0.2.6
//     spin:up@3.5.0
//     wasi:io@0.2.0-rc-2023-11-10
//     wasi:clocks@0.2.0-rc-2023-11-10
//     wasi:filesystem@0.2.0-rc-2023-11-10
//     wasi:sockets@0.2.0-rc-2023-11-10
//     wasi:random@0.2.0-rc-2023-11-10
//     wasi:cli@0.2.0-rc-2023-11-10
//     wasi:http@0.2.0-rc-2023-11-10

package wasi_cli_0_3_0_rc_2025_09_16_stdin

import (
	"runtime"
	"unsafe"

	"github.com/bytecodealliance/wit-bindgen/wit_runtime"
	"github.com/bytecodealliance/wit-bindgen/wit_types"
	"github.com/spinframework/spin-go-sdk/v4/wit_component/wasi_cli_0_3_0_rc_2025_09_16_types"
)

//go:wasmimport wasi:cli/stdin@0.3.0-rc-2025-09-16 [stream-new-0]read-via-stream
func wasm_stream_new_u8() uint64

//go:wasmimport wasi:cli/stdin@0.3.0-rc-2025-09-16 [async-lower][stream-read-0]read-via-stream
func wasm_stream_read_u8(handle int32, item unsafe.Pointer, count uint32) uint32

//go:wasmimport wasi:cli/stdin@0.3.0-rc-2025-09-16 [async-lower][stream-write-0]read-via-stream
func wasm_stream_write_u8(handle int32, item unsafe.Pointer, count uint32) uint32

//go:wasmimport wasi:cli/stdin@0.3.0-rc-2025-09-16 [stream-drop-readable-0]read-via-stream
func wasm_stream_drop_readable_u8(handle int32)

//go:wasmimport wasi:cli/stdin@0.3.0-rc-2025-09-16 [stream-drop-writable-0]read-via-stream
func wasm_stream_drop_writable_u8(handle int32)

var wasm_stream_vtable_u8 = wit_types.StreamVtable[uint8]{
	1,
	1,
	wasm_stream_read_u8,
	wasm_stream_write_u8,
	nil,
	nil,
	wasm_stream_drop_readable_u8,
	wasm_stream_drop_writable_u8,
	nil,
	nil,
}

func MakeStreamU8() (*wit_types.StreamWriter[uint8], *wit_types.StreamReader[uint8]) {
	pair := wasm_stream_new_u8()
	return wit_types.MakeStreamWriter[uint8](&wasm_stream_vtable_u8, int32(pair>>32)),
		wit_types.MakeStreamReader[uint8](&wasm_stream_vtable_u8, int32(pair&0xFFFFFFFF))
}

func LiftStreamU8(handle int32) *wit_types.StreamReader[uint8] {
	return wit_types.MakeStreamReader[uint8](&wasm_stream_vtable_u8, handle)
}

//go:wasmimport wasi:cli/stdin@0.3.0-rc-2025-09-16 [future-new-1]read-via-stream
func wasm_future_new_result_unit_wasi_cli_0_3_0_rc_2025_09_16_types_error_code() uint64

//go:wasmimport wasi:cli/stdin@0.3.0-rc-2025-09-16 [async-lower][future-read-1]read-via-stream
func wasm_future_read_result_unit_wasi_cli_0_3_0_rc_2025_09_16_types_error_code(handle int32, item unsafe.Pointer) uint32

//go:wasmimport wasi:cli/stdin@0.3.0-rc-2025-09-16 [async-lower][future-write-1]read-via-stream
func wasm_future_write_result_unit_wasi_cli_0_3_0_rc_2025_09_16_types_error_code(handle int32, item unsafe.Pointer) uint32

//go:wasmimport wasi:cli/stdin@0.3.0-rc-2025-09-16 [future-drop-readable-1]read-via-stream
func wasm_future_drop_readable_result_unit_wasi_cli_0_3_0_rc_2025_09_16_types_error_code(handle int32)

//go:wasmimport wasi:cli/stdin@0.3.0-rc-2025-09-16 [future-drop-writable-1]read-via-stream
func wasm_future_drop_writable_result_unit_wasi_cli_0_3_0_rc_2025_09_16_types_error_code(handle int32)

func wasm_future_lift_result_unit_wasi_cli_0_3_0_rc_2025_09_16_types_error_code(src unsafe.Pointer) wit_types.Result[wit_types.Unit, wasi_cli_0_3_0_rc_2025_09_16_types.ErrorCode] {
	var result wit_types.Result[wit_types.Unit, wasi_cli_0_3_0_rc_2025_09_16_types.ErrorCode]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(src), 0))) {
	case 0:

		result = wit_types.Ok[wit_types.Unit, wasi_cli_0_3_0_rc_2025_09_16_types.ErrorCode](wit_types.Unit{})
	case 1:

		result = wit_types.Err[wit_types.Unit, wasi_cli_0_3_0_rc_2025_09_16_types.ErrorCode](uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(src), 1)))))
	default:
		panic("unreachable")
	}

	return result
}

func wasm_future_lower_result_unit_wasi_cli_0_3_0_rc_2025_09_16_types_error_code(
	pinner *runtime.Pinner,
	value wit_types.Result[wit_types.Unit, wasi_cli_0_3_0_rc_2025_09_16_types.ErrorCode],
	dst unsafe.Pointer,
) func() {

	switch value.Tag() {
	case wit_types.ResultOk:

		*(*int8)(unsafe.Add(unsafe.Pointer(dst), 0)) = int8(int32(0))

	case wit_types.ResultErr:
		payload := value.Err()
		*(*int8)(unsafe.Add(unsafe.Pointer(dst), 0)) = int8(int32(1))
		*(*int8)(unsafe.Add(unsafe.Pointer(dst), 1)) = int8(int32(payload))

	default:
		panic("unreachable")
	}

	return func() {}
}

var wasm_future_vtable_result_unit_wasi_cli_0_3_0_rc_2025_09_16_types_error_code = wit_types.FutureVtable[wit_types.Result[wit_types.Unit, wasi_cli_0_3_0_rc_2025_09_16_types.ErrorCode]]{
	2,
	1,
	wasm_future_read_result_unit_wasi_cli_0_3_0_rc_2025_09_16_types_error_code,
	wasm_future_write_result_unit_wasi_cli_0_3_0_rc_2025_09_16_types_error_code,
	nil,
	nil,
	wasm_future_drop_readable_result_unit_wasi_cli_0_3_0_rc_2025_09_16_types_error_code,
	wasm_future_drop_writable_result_unit_wasi_cli_0_3_0_rc_2025_09_16_types_error_code,
	wasm_future_lift_result_unit_wasi_cli_0_3_0_rc_2025_09_16_types_error_code,
	wasm_future_lower_result_unit_wasi_cli_0_3_0_rc_2025_09_16_types_error_code,
}

func MakeFutureResultUnitWasiCli030Rc20250916TypesErrorCode() (*wit_types.FutureWriter[wit_types.Result[wit_types.Unit, wasi_cli_0_3_0_rc_2025_09_16_types.ErrorCode]], *wit_types.FutureReader[wit_types.Result[wit_types.Unit, wasi_cli_0_3_0_rc_2025_09_16_types.ErrorCode]]) {
	pair := wasm_future_new_result_unit_wasi_cli_0_3_0_rc_2025_09_16_types_error_code()
	return wit_types.MakeFutureWriter[wit_types.Result[wit_types.Unit, wasi_cli_0_3_0_rc_2025_09_16_types.ErrorCode]](&wasm_future_vtable_result_unit_wasi_cli_0_3_0_rc_2025_09_16_types_error_code, int32(pair>>32)),
		wit_types.MakeFutureReader[wit_types.Result[wit_types.Unit, wasi_cli_0_3_0_rc_2025_09_16_types.ErrorCode]](&wasm_future_vtable_result_unit_wasi_cli_0_3_0_rc_2025_09_16_types_error_code, int32(pair&0xFFFFFFFF))
}

func LiftFutureResultUnitWasiCli030Rc20250916TypesErrorCode(handle int32) *wit_types.FutureReader[wit_types.Result[wit_types.Unit, wasi_cli_0_3_0_rc_2025_09_16_types.ErrorCode]] {
	return wit_types.MakeFutureReader[wit_types.Result[wit_types.Unit, wasi_cli_0_3_0_rc_2025_09_16_types.ErrorCode]](&wasm_future_vtable_result_unit_wasi_cli_0_3_0_rc_2025_09_16_types_error_code, handle)
}

type ErrorCode = wasi_cli_0_3_0_rc_2025_09_16_types.ErrorCode

//go:wasmimport wasi:cli/stdin@0.3.0-rc-2025-09-16 read-via-stream
func wasm_import_read_via_stream(arg0 uintptr)

func ReadViaStream() (*wit_types.StreamReader[uint8], *wit_types.FutureReader[wit_types.Result[wit_types.Unit, wasi_cli_0_3_0_rc_2025_09_16_types.ErrorCode]]) {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(wit_runtime.Allocate(pinner, 8, 4))
	wasm_import_read_via_stream(returnArea)
	result := wit_types.Tuple2[*wit_types.StreamReader[uint8], *wit_types.FutureReader[wit_types.Result[wit_types.Unit, wasi_cli_0_3_0_rc_2025_09_16_types.ErrorCode]]]{LiftStreamU8(*(*int32)(unsafe.Add(unsafe.Pointer(returnArea), 0))), LiftFutureResultUnitWasiCli030Rc20250916TypesErrorCode(*(*int32)(unsafe.Add(unsafe.Pointer(returnArea), 4)))}
	tuple := result
	return tuple.F0, tuple.F1

}
