// Generated by `wit-bindgen` 0.50.0. DO NOT EDIT!
//
// This code was generated from the following packages:
//     fermyon:spin
//     wasi:io@0.2.0
//     wasi:clocks@0.2.0
//     wasi:random@0.2.0
//     wasi:filesystem@0.2.0
//     wasi:sockets@0.2.0
//     wasi:cli@0.2.0
//     wasi:http@0.2.0
//     wasi:io@0.2.0-rc-2023-10-18
//     wasi:clocks@0.2.0-rc-2023-10-18
//     wasi:random@0.2.0-rc-2023-10-18
//     wasi:filesystem@0.2.0-rc-2023-10-18
//     wasi:sockets@0.2.0-rc-2023-10-18
//     wasi:cli@0.2.0-rc-2023-10-18
//     wasi:http@0.2.0-rc-2023-10-18
//     fermyon:spin@2.0.0
//     wasi:keyvalue@0.2.0-draft2
//     spin:postgres@3.0.0
//     wasi:config@0.2.0-draft-2024-09-27
//     fermyon:spin@3.0.0
//     spin:postgres@4.0.0
//     spin:sqlite@3.0.0
//     wasi:io@0.2.3
//     wasi:clocks@0.2.3
//     wasi:filesystem@0.2.3
//     wasi:sockets@0.2.3
//     wasi:random@0.2.3
//     wasi:cli@0.2.3
//     wasi:http@0.2.3
//     spin:up@3.2.0
//     spin:up@3.4.0
//     wasi:clocks@0.3.0-rc-2025-09-16
//     wasi:random@0.3.0-rc-2025-09-16
//     wasi:filesystem@0.3.0-rc-2025-09-16
//     wasi:sockets@0.3.0-rc-2025-09-16
//     wasi:cli@0.3.0-rc-2025-09-16
//     wasi:http@0.3.0-rc-2025-09-16
//     wasi:io@0.2.6
//     wasi:clocks@0.2.6
//     wasi:filesystem@0.2.6
//     wasi:sockets@0.2.6
//     wasi:random@0.2.6
//     wasi:cli@0.2.6
//     wasi:http@0.2.6
//     spin:up@3.5.0
//     wasi:io@0.2.0-rc-2023-11-10
//     wasi:clocks@0.2.0-rc-2023-11-10
//     wasi:filesystem@0.2.0-rc-2023-11-10
//     wasi:sockets@0.2.0-rc-2023-11-10
//     wasi:random@0.2.0-rc-2023-11-10
//     wasi:cli@0.2.0-rc-2023-11-10
//     wasi:http@0.2.0-rc-2023-11-10

package wasi_http_0_3_0_rc_2025_09_16_handler

import (
	"runtime"
	"unsafe"

	"github.com/bytecodealliance/wit-bindgen/wit_async"
	"github.com/bytecodealliance/wit-bindgen/wit_runtime"
	"github.com/bytecodealliance/wit-bindgen/wit_types"
	"github.com/spinframework/spin-go-sdk/v4/wit_component/wasi_http_0_3_0_rc_2025_09_16_types"
)

type Request = wasi_http_0_3_0_rc_2025_09_16_types.Request
type Response = wasi_http_0_3_0_rc_2025_09_16_types.Response
type ErrorCode = wasi_http_0_3_0_rc_2025_09_16_types.ErrorCode

//go:wasmimport wasi:http/handler@0.3.0-rc-2025-09-16 [async-lower]handle
func wasm_import_handle(arg0 int32, arg1 uintptr) int32

func Handle(request *wasi_http_0_3_0_rc_2025_09_16_types.Request) wit_types.Result[*wasi_http_0_3_0_rc_2025_09_16_types.Response, wasi_http_0_3_0_rc_2025_09_16_types.ErrorCode] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(wit_runtime.Allocate(pinner, (24 + 4*4), 8))

	wit_async.SubtaskWait(uint32(wasm_import_handle((request).TakeHandle(), returnArea)))
	var result wit_types.Result[*wasi_http_0_3_0_rc_2025_09_16_types.Response, wasi_http_0_3_0_rc_2025_09_16_types.ErrorCode]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		result = wit_types.Ok[*wasi_http_0_3_0_rc_2025_09_16_types.Response, wasi_http_0_3_0_rc_2025_09_16_types.ErrorCode](wasi_http_0_3_0_rc_2025_09_16_types.ResponseFromOwnHandle(int32(uintptr(*(*int32)(unsafe.Add(unsafe.Pointer(returnArea), 8))))))
	case 1:
		var variant wasi_http_0_3_0_rc_2025_09_16_types.ErrorCode
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 8))) {
		case 0:

			variant = wasi_http_0_3_0_rc_2025_09_16_types.MakeErrorCodeDnsTimeout()

		case 1:
			var option wit_types.Option[string]
			switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))) {
			case 0:

				option = wit_types.None[string]()
			case 1:
				value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 2*4))))

				option = wit_types.Some[string](value)
			default:
				panic("unreachable")
			}
			var option0 wit_types.Option[uint16]
			switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 3*4)))) {
			case 0:

				option0 = wit_types.None[uint16]()
			case 1:

				option0 = wit_types.Some[uint16](uint16(uint16(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (18 + 3*4))))))
			default:
				panic("unreachable")
			}

			variant = wasi_http_0_3_0_rc_2025_09_16_types.MakeErrorCodeDnsError(wasi_http_0_3_0_rc_2025_09_16_types.DnsErrorPayload{option, option0})

		case 2:

			variant = wasi_http_0_3_0_rc_2025_09_16_types.MakeErrorCodeDestinationNotFound()

		case 3:

			variant = wasi_http_0_3_0_rc_2025_09_16_types.MakeErrorCodeDestinationUnavailable()

		case 4:

			variant = wasi_http_0_3_0_rc_2025_09_16_types.MakeErrorCodeDestinationIpProhibited()

		case 5:

			variant = wasi_http_0_3_0_rc_2025_09_16_types.MakeErrorCodeDestinationIpUnroutable()

		case 6:

			variant = wasi_http_0_3_0_rc_2025_09_16_types.MakeErrorCodeConnectionRefused()

		case 7:

			variant = wasi_http_0_3_0_rc_2025_09_16_types.MakeErrorCodeConnectionTerminated()

		case 8:

			variant = wasi_http_0_3_0_rc_2025_09_16_types.MakeErrorCodeConnectionTimeout()

		case 9:

			variant = wasi_http_0_3_0_rc_2025_09_16_types.MakeErrorCodeConnectionReadTimeout()

		case 10:

			variant = wasi_http_0_3_0_rc_2025_09_16_types.MakeErrorCodeConnectionWriteTimeout()

		case 11:

			variant = wasi_http_0_3_0_rc_2025_09_16_types.MakeErrorCodeConnectionLimitReached()

		case 12:

			variant = wasi_http_0_3_0_rc_2025_09_16_types.MakeErrorCodeTlsProtocolError()

		case 13:

			variant = wasi_http_0_3_0_rc_2025_09_16_types.MakeErrorCodeTlsCertificateError()

		case 14:
			var option1 wit_types.Option[uint8]
			switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))) {
			case 0:

				option1 = wit_types.None[uint8]()
			case 1:

				option1 = wit_types.Some[uint8](uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 17)))))
			default:
				panic("unreachable")
			}
			var option3 wit_types.Option[string]
			switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4)))) {
			case 0:

				option3 = wit_types.None[string]()
			case 1:
				value2 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 2*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 3*4))))

				option3 = wit_types.Some[string](value2)
			default:
				panic("unreachable")
			}

			variant = wasi_http_0_3_0_rc_2025_09_16_types.MakeErrorCodeTlsAlertReceived(wasi_http_0_3_0_rc_2025_09_16_types.TlsAlertReceivedPayload{option1, option3})

		case 15:

			variant = wasi_http_0_3_0_rc_2025_09_16_types.MakeErrorCodeHttpRequestDenied()

		case 16:

			variant = wasi_http_0_3_0_rc_2025_09_16_types.MakeErrorCodeHttpRequestLengthRequired()

		case 17:
			var option4 wit_types.Option[uint64]
			switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))) {
			case 0:

				option4 = wit_types.None[uint64]()
			case 1:

				option4 = wit_types.Some[uint64](uint64(*(*int64)(unsafe.Add(unsafe.Pointer(returnArea), 24))))
			default:
				panic("unreachable")
			}

			variant = wasi_http_0_3_0_rc_2025_09_16_types.MakeErrorCodeHttpRequestBodySize(option4)

		case 18:

			variant = wasi_http_0_3_0_rc_2025_09_16_types.MakeErrorCodeHttpRequestMethodInvalid()

		case 19:

			variant = wasi_http_0_3_0_rc_2025_09_16_types.MakeErrorCodeHttpRequestUriInvalid()

		case 20:

			variant = wasi_http_0_3_0_rc_2025_09_16_types.MakeErrorCodeHttpRequestUriTooLong()

		case 21:
			var option5 wit_types.Option[uint32]
			switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))) {
			case 0:

				option5 = wit_types.None[uint32]()
			case 1:

				option5 = wit_types.Some[uint32](uint32(*(*int32)(unsafe.Add(unsafe.Pointer(returnArea), 20))))
			default:
				panic("unreachable")
			}

			variant = wasi_http_0_3_0_rc_2025_09_16_types.MakeErrorCodeHttpRequestHeaderSectionSize(option5)

		case 22:
			var option9 wit_types.Option[wasi_http_0_3_0_rc_2025_09_16_types.FieldSizePayload]
			switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))) {
			case 0:

				option9 = wit_types.None[wasi_http_0_3_0_rc_2025_09_16_types.FieldSizePayload]()
			case 1:
				var option7 wit_types.Option[string]
				switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4)))) {
				case 0:

					option7 = wit_types.None[string]()
				case 1:
					value6 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 2*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 3*4))))

					option7 = wit_types.Some[string](value6)
				default:
					panic("unreachable")
				}
				var option8 wit_types.Option[uint32]
				switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 4*4)))) {
				case 0:

					option8 = wit_types.None[uint32]()
				case 1:

					option8 = wit_types.Some[uint32](uint32(*(*int32)(unsafe.Add(unsafe.Pointer(returnArea), (20 + 4*4)))))
				default:
					panic("unreachable")
				}

				option9 = wit_types.Some[wasi_http_0_3_0_rc_2025_09_16_types.FieldSizePayload](wasi_http_0_3_0_rc_2025_09_16_types.FieldSizePayload{option7, option8})
			default:
				panic("unreachable")
			}

			variant = wasi_http_0_3_0_rc_2025_09_16_types.MakeErrorCodeHttpRequestHeaderSize(option9)

		case 23:
			var option10 wit_types.Option[uint32]
			switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))) {
			case 0:

				option10 = wit_types.None[uint32]()
			case 1:

				option10 = wit_types.Some[uint32](uint32(*(*int32)(unsafe.Add(unsafe.Pointer(returnArea), 20))))
			default:
				panic("unreachable")
			}

			variant = wasi_http_0_3_0_rc_2025_09_16_types.MakeErrorCodeHttpRequestTrailerSectionSize(option10)

		case 24:
			var option12 wit_types.Option[string]
			switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))) {
			case 0:

				option12 = wit_types.None[string]()
			case 1:
				value11 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 2*4))))

				option12 = wit_types.Some[string](value11)
			default:
				panic("unreachable")
			}
			var option13 wit_types.Option[uint32]
			switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 3*4)))) {
			case 0:

				option13 = wit_types.None[uint32]()
			case 1:

				option13 = wit_types.Some[uint32](uint32(*(*int32)(unsafe.Add(unsafe.Pointer(returnArea), (20 + 3*4)))))
			default:
				panic("unreachable")
			}

			variant = wasi_http_0_3_0_rc_2025_09_16_types.MakeErrorCodeHttpRequestTrailerSize(wasi_http_0_3_0_rc_2025_09_16_types.FieldSizePayload{option12, option13})

		case 25:

			variant = wasi_http_0_3_0_rc_2025_09_16_types.MakeErrorCodeHttpResponseIncomplete()

		case 26:
			var option14 wit_types.Option[uint32]
			switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))) {
			case 0:

				option14 = wit_types.None[uint32]()
			case 1:

				option14 = wit_types.Some[uint32](uint32(*(*int32)(unsafe.Add(unsafe.Pointer(returnArea), 20))))
			default:
				panic("unreachable")
			}

			variant = wasi_http_0_3_0_rc_2025_09_16_types.MakeErrorCodeHttpResponseHeaderSectionSize(option14)

		case 27:
			var option16 wit_types.Option[string]
			switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))) {
			case 0:

				option16 = wit_types.None[string]()
			case 1:
				value15 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 2*4))))

				option16 = wit_types.Some[string](value15)
			default:
				panic("unreachable")
			}
			var option17 wit_types.Option[uint32]
			switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 3*4)))) {
			case 0:

				option17 = wit_types.None[uint32]()
			case 1:

				option17 = wit_types.Some[uint32](uint32(*(*int32)(unsafe.Add(unsafe.Pointer(returnArea), (20 + 3*4)))))
			default:
				panic("unreachable")
			}

			variant = wasi_http_0_3_0_rc_2025_09_16_types.MakeErrorCodeHttpResponseHeaderSize(wasi_http_0_3_0_rc_2025_09_16_types.FieldSizePayload{option16, option17})

		case 28:
			var option18 wit_types.Option[uint64]
			switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))) {
			case 0:

				option18 = wit_types.None[uint64]()
			case 1:

				option18 = wit_types.Some[uint64](uint64(*(*int64)(unsafe.Add(unsafe.Pointer(returnArea), 24))))
			default:
				panic("unreachable")
			}

			variant = wasi_http_0_3_0_rc_2025_09_16_types.MakeErrorCodeHttpResponseBodySize(option18)

		case 29:
			var option19 wit_types.Option[uint32]
			switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))) {
			case 0:

				option19 = wit_types.None[uint32]()
			case 1:

				option19 = wit_types.Some[uint32](uint32(*(*int32)(unsafe.Add(unsafe.Pointer(returnArea), 20))))
			default:
				panic("unreachable")
			}

			variant = wasi_http_0_3_0_rc_2025_09_16_types.MakeErrorCodeHttpResponseTrailerSectionSize(option19)

		case 30:
			var option21 wit_types.Option[string]
			switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))) {
			case 0:

				option21 = wit_types.None[string]()
			case 1:
				value20 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 2*4))))

				option21 = wit_types.Some[string](value20)
			default:
				panic("unreachable")
			}
			var option22 wit_types.Option[uint32]
			switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 3*4)))) {
			case 0:

				option22 = wit_types.None[uint32]()
			case 1:

				option22 = wit_types.Some[uint32](uint32(*(*int32)(unsafe.Add(unsafe.Pointer(returnArea), (20 + 3*4)))))
			default:
				panic("unreachable")
			}

			variant = wasi_http_0_3_0_rc_2025_09_16_types.MakeErrorCodeHttpResponseTrailerSize(wasi_http_0_3_0_rc_2025_09_16_types.FieldSizePayload{option21, option22})

		case 31:
			var option24 wit_types.Option[string]
			switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))) {
			case 0:

				option24 = wit_types.None[string]()
			case 1:
				value23 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 2*4))))

				option24 = wit_types.Some[string](value23)
			default:
				panic("unreachable")
			}

			variant = wasi_http_0_3_0_rc_2025_09_16_types.MakeErrorCodeHttpResponseTransferCoding(option24)

		case 32:
			var option26 wit_types.Option[string]
			switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))) {
			case 0:

				option26 = wit_types.None[string]()
			case 1:
				value25 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 2*4))))

				option26 = wit_types.Some[string](value25)
			default:
				panic("unreachable")
			}

			variant = wasi_http_0_3_0_rc_2025_09_16_types.MakeErrorCodeHttpResponseContentCoding(option26)

		case 33:

			variant = wasi_http_0_3_0_rc_2025_09_16_types.MakeErrorCodeHttpResponseTimeout()

		case 34:

			variant = wasi_http_0_3_0_rc_2025_09_16_types.MakeErrorCodeHttpUpgradeFailed()

		case 35:

			variant = wasi_http_0_3_0_rc_2025_09_16_types.MakeErrorCodeHttpProtocolError()

		case 36:

			variant = wasi_http_0_3_0_rc_2025_09_16_types.MakeErrorCodeLoopDetected()

		case 37:

			variant = wasi_http_0_3_0_rc_2025_09_16_types.MakeErrorCodeConfigurationError()

		case 38:
			var option28 wit_types.Option[string]
			switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))) {
			case 0:

				option28 = wit_types.None[string]()
			case 1:
				value27 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 2*4))))

				option28 = wit_types.Some[string](value27)
			default:
				panic("unreachable")
			}

			variant = wasi_http_0_3_0_rc_2025_09_16_types.MakeErrorCodeInternalError(option28)

		default:
			panic("unreachable")
		}

		result = wit_types.Err[*wasi_http_0_3_0_rc_2025_09_16_types.Response, wasi_http_0_3_0_rc_2025_09_16_types.ErrorCode](variant)
	default:
		panic("unreachable")
	}

	return result

}
