// Generated by `wit-bindgen` 0.50.0. DO NOT EDIT!
package wasi_http_0_2_0_incoming_handler

import (
	"github.com/spinframework/spin-go-sdk/v3/wit_component/wasi_http_0_2_0_types"
)

type IncomingRequest = wasi_http_0_2_0_types.IncomingRequest
type ResponseOutparam = wasi_http_0_2_0_types.ResponseOutparam
