// Generated by `wit-bindgen` 0.50.0. DO NOT EDIT!
package wit_types

type Tuple2[T0 any, T1 any] struct {
	F0 T0
	F1 T1
}
type Tuple3[T0 any, T1 any, T2 any] struct {
	F0 T0
	F1 T1
	F2 T2
}
type Tuple4[T0 any, T1 any, T2 any, T3 any] struct {
	F0 T0
	F1 T1
	F2 T2
	F3 T3
}
type Tuple7[T0 any, T1 any, T2 any, T3 any, T4 any, T5 any, T6 any] struct {
	F0 T0
	F1 T1
	F2 T2
	F3 T3
	F4 T4
	F5 T5
	F6 T6
}
type Tuple8[T0 any, T1 any, T2 any, T3 any, T4 any, T5 any, T6 any, T7 any] struct {
	F0 T0
	F1 T1
	F2 T2
	F3 T3
	F4 T4
	F5 T5
	F6 T6
	F7 T7
}
