// Generated by `wit-bindgen` 0.50.0. DO NOT EDIT!
//
// This code was generated from the following packages:
//     fermyon:spin
//     wasi:io@0.2.0
//     wasi:clocks@0.2.0
//     wasi:random@0.2.0
//     wasi:filesystem@0.2.0
//     wasi:sockets@0.2.0
//     wasi:cli@0.2.0
//     wasi:http@0.2.0
//     wasi:io@0.2.0-rc-2023-10-18
//     wasi:clocks@0.2.0-rc-2023-10-18
//     wasi:random@0.2.0-rc-2023-10-18
//     wasi:filesystem@0.2.0-rc-2023-10-18
//     wasi:sockets@0.2.0-rc-2023-10-18
//     wasi:cli@0.2.0-rc-2023-10-18
//     wasi:http@0.2.0-rc-2023-10-18
//     fermyon:spin@2.0.0
//     wasi:keyvalue@0.2.0-draft2
//     spin:postgres@3.0.0
//     wasi:config@0.2.0-draft-2024-09-27
//     fermyon:spin@3.0.0
//     spin:postgres@4.0.0
//     spin:sqlite@3.0.0
//     wasi:io@0.2.3
//     wasi:clocks@0.2.3
//     wasi:filesystem@0.2.3
//     wasi:sockets@0.2.3
//     wasi:random@0.2.3
//     wasi:cli@0.2.3
//     wasi:http@0.2.3
//     spin:up@3.2.0
//     spin:up@3.4.0
//     wasi:clocks@0.3.0-rc-2025-09-16
//     wasi:random@0.3.0-rc-2025-09-16
//     wasi:filesystem@0.3.0-rc-2025-09-16
//     wasi:sockets@0.3.0-rc-2025-09-16
//     wasi:cli@0.3.0-rc-2025-09-16
//     wasi:http@0.3.0-rc-2025-09-16
//     wasi:io@0.2.6
//     wasi:clocks@0.2.6
//     wasi:filesystem@0.2.6
//     wasi:sockets@0.2.6
//     wasi:random@0.2.6
//     wasi:cli@0.2.6
//     wasi:http@0.2.6
//     spin:up@3.5.0
//     wasi:io@0.2.0-rc-2023-11-10
//     wasi:clocks@0.2.0-rc-2023-11-10
//     wasi:filesystem@0.2.0-rc-2023-11-10
//     wasi:sockets@0.2.0-rc-2023-11-10
//     wasi:random@0.2.0-rc-2023-11-10
//     wasi:cli@0.2.0-rc-2023-11-10
//     wasi:http@0.2.0-rc-2023-11-10

package wasi_sockets_0_3_0_rc_2025_09_16_types

import (
        "github.com/bytecodealliance/wit-bindgen/wit_async"
"github.com/bytecodealliance/wit-bindgen/wit_runtime"
"github.com/bytecodealliance/wit-bindgen/wit_types"
"unsafe"
"runtime"
)


//go:wasmimport wasi:sockets/types@0.3.0-rc-2025-09-16 [stream-new-0][method]tcp-socket.listen
func wasm_stream_new_tcp_socket() uint64

//go:wasmimport wasi:sockets/types@0.3.0-rc-2025-09-16 [async-lower][stream-read-0][method]tcp-socket.listen
func wasm_stream_read_tcp_socket(handle int32, item unsafe.Pointer, count uint32) uint32

//go:wasmimport wasi:sockets/types@0.3.0-rc-2025-09-16 [async-lower][stream-write-0][method]tcp-socket.listen
func wasm_stream_write_tcp_socket(handle int32, item unsafe.Pointer, count uint32) uint32

//go:wasmimport wasi:sockets/types@0.3.0-rc-2025-09-16 [stream-drop-readable-0][method]tcp-socket.listen
func wasm_stream_drop_readable_tcp_socket(handle int32)

//go:wasmimport wasi:sockets/types@0.3.0-rc-2025-09-16 [stream-drop-writable-0][method]tcp-socket.listen
func wasm_stream_drop_writable_tcp_socket(handle int32)

func wasm_stream_lift_tcp_socket(src unsafe.Pointer) *TcpSocket {
        
	return TcpSocketFromOwnHandle(int32(uintptr(*(*int32)(unsafe.Add(unsafe.Pointer(src), 0)))))
}


func wasm_stream_lower_tcp_socket(
        pinner *runtime.Pinner,
        value *TcpSocket,
        dst unsafe.Pointer,
) func() {
        lifters := make([]func(), 0, 1)
resource := value
handle := resource.TakeHandle()
lifters = append(lifters, func() {
        resource.SetHandle(handle)
})
*(*int32)(unsafe.Add(unsafe.Pointer(dst), 0)) = handle

return func() {
        for _, lifter := range lifters {
                lifter()
        }
}
}


var wasm_stream_vtable_tcp_socket = wit_types.StreamVtable[*TcpSocket]{
	4,
	4,
	wasm_stream_read_tcp_socket,
	wasm_stream_write_tcp_socket,
	nil,
	nil,
	wasm_stream_drop_readable_tcp_socket,
	wasm_stream_drop_writable_tcp_socket,
	wasm_stream_lift_tcp_socket,
	wasm_stream_lower_tcp_socket,
}

func MakeStreamTcpSocket() (*wit_types.StreamWriter[*TcpSocket], *wit_types.StreamReader[*TcpSocket]) {
	pair := wasm_stream_new_tcp_socket()
	return wit_types.MakeStreamWriter[*TcpSocket](&wasm_stream_vtable_tcp_socket, int32(pair >> 32)),
		wit_types.MakeStreamReader[*TcpSocket](&wasm_stream_vtable_tcp_socket, int32(pair & 0xFFFFFFFF))
}

func LiftStreamTcpSocket(handle int32) *wit_types.StreamReader[*TcpSocket] {
	return wit_types.MakeStreamReader[*TcpSocket](&wasm_stream_vtable_tcp_socket, handle)
}

//go:wasmimport wasi:sockets/types@0.3.0-rc-2025-09-16 [stream-new-0][method]tcp-socket.send
func wasm_stream_new_u8() uint64

//go:wasmimport wasi:sockets/types@0.3.0-rc-2025-09-16 [async-lower][stream-read-0][method]tcp-socket.send
func wasm_stream_read_u8(handle int32, item unsafe.Pointer, count uint32) uint32

//go:wasmimport wasi:sockets/types@0.3.0-rc-2025-09-16 [async-lower][stream-write-0][method]tcp-socket.send
func wasm_stream_write_u8(handle int32, item unsafe.Pointer, count uint32) uint32

//go:wasmimport wasi:sockets/types@0.3.0-rc-2025-09-16 [stream-drop-readable-0][method]tcp-socket.send
func wasm_stream_drop_readable_u8(handle int32)

//go:wasmimport wasi:sockets/types@0.3.0-rc-2025-09-16 [stream-drop-writable-0][method]tcp-socket.send
func wasm_stream_drop_writable_u8(handle int32)





var wasm_stream_vtable_u8 = wit_types.StreamVtable[uint8]{
	1,
	1,
	wasm_stream_read_u8,
	wasm_stream_write_u8,
	nil,
	nil,
	wasm_stream_drop_readable_u8,
	wasm_stream_drop_writable_u8,
	nil,
	nil,
}

func MakeStreamU8() (*wit_types.StreamWriter[uint8], *wit_types.StreamReader[uint8]) {
	pair := wasm_stream_new_u8()
	return wit_types.MakeStreamWriter[uint8](&wasm_stream_vtable_u8, int32(pair >> 32)),
		wit_types.MakeStreamReader[uint8](&wasm_stream_vtable_u8, int32(pair & 0xFFFFFFFF))
}

func LiftStreamU8(handle int32) *wit_types.StreamReader[uint8] {
	return wit_types.MakeStreamReader[uint8](&wasm_stream_vtable_u8, handle)
}

//go:wasmimport wasi:sockets/types@0.3.0-rc-2025-09-16 [future-new-1][method]tcp-socket.receive
func wasm_future_new_result_unit_error_code() uint64

//go:wasmimport wasi:sockets/types@0.3.0-rc-2025-09-16 [async-lower][future-read-1][method]tcp-socket.receive
func wasm_future_read_result_unit_error_code(handle int32, item unsafe.Pointer) uint32

//go:wasmimport wasi:sockets/types@0.3.0-rc-2025-09-16 [async-lower][future-write-1][method]tcp-socket.receive
func wasm_future_write_result_unit_error_code(handle int32, item unsafe.Pointer) uint32

//go:wasmimport wasi:sockets/types@0.3.0-rc-2025-09-16 [future-drop-readable-1][method]tcp-socket.receive
func wasm_future_drop_readable_result_unit_error_code(handle int32)

//go:wasmimport wasi:sockets/types@0.3.0-rc-2025-09-16 [future-drop-writable-1][method]tcp-socket.receive
func wasm_future_drop_writable_result_unit_error_code(handle int32)

func wasm_future_lift_result_unit_error_code(src unsafe.Pointer) wit_types.Result[wit_types.Unit, ErrorCode] {
        var result wit_types.Result[wit_types.Unit, ErrorCode]
switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(src), 0))) {
case 0:
        
        result = wit_types.Ok[wit_types.Unit, ErrorCode](wit_types.Unit{})
case 1:
        
        result = wit_types.Err[wit_types.Unit, ErrorCode](uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(src), 1)))))
default:
        panic("unreachable")
}

	return result
}


func wasm_future_lower_result_unit_error_code(
        pinner *runtime.Pinner,
        value wit_types.Result[wit_types.Unit, ErrorCode],
        dst unsafe.Pointer,
) func() {
        
switch value.Tag() {
case wit_types.ResultOk:
        
        *(*int8)(unsafe.Add(unsafe.Pointer(dst), 0)) = int8(int32(0))

        
case wit_types.ResultErr:
        payload := value.Err()
        *(*int8)(unsafe.Add(unsafe.Pointer(dst), 0)) = int8(int32(1))
*(*int8)(unsafe.Add(unsafe.Pointer(dst), 1)) = int8(int32(payload))

        
default:
        panic("unreachable")
}

return func() {}
}


var wasm_future_vtable_result_unit_error_code = wit_types.FutureVtable[wit_types.Result[wit_types.Unit, ErrorCode]]{
	2,
	1,
	wasm_future_read_result_unit_error_code,
	wasm_future_write_result_unit_error_code,
	nil,
	nil,
	wasm_future_drop_readable_result_unit_error_code,
	wasm_future_drop_writable_result_unit_error_code,
	wasm_future_lift_result_unit_error_code,
	wasm_future_lower_result_unit_error_code,
}

func MakeFutureResultUnitErrorCode() (*wit_types.FutureWriter[wit_types.Result[wit_types.Unit, ErrorCode]], *wit_types.FutureReader[wit_types.Result[wit_types.Unit, ErrorCode]]) {
	pair := wasm_future_new_result_unit_error_code()
	return wit_types.MakeFutureWriter[wit_types.Result[wit_types.Unit, ErrorCode]](&wasm_future_vtable_result_unit_error_code, int32(pair >> 32)),
		wit_types.MakeFutureReader[wit_types.Result[wit_types.Unit, ErrorCode]](&wasm_future_vtable_result_unit_error_code, int32(pair & 0xFFFFFFFF))
}

func LiftFutureResultUnitErrorCode(handle int32) *wit_types.FutureReader[wit_types.Result[wit_types.Unit, ErrorCode]] {
	return wit_types.MakeFutureReader[wit_types.Result[wit_types.Unit, ErrorCode]](&wasm_future_vtable_result_unit_error_code, handle)
}
type Duration = uint64

const (
        // Unknown error
ErrorCodeUnknown uint8 = 0
// Access denied.
// 
// POSIX equivalent: EACCES, EPERM
ErrorCodeAccessDenied uint8 = 1
// The operation is not supported.
// 
// POSIX equivalent: EOPNOTSUPP
ErrorCodeNotSupported uint8 = 2
// One of the arguments is invalid.
// 
// POSIX equivalent: EINVAL
ErrorCodeInvalidArgument uint8 = 3
// Not enough memory to complete the operation.
// 
// POSIX equivalent: ENOMEM, ENOBUFS, EAI_MEMORY
ErrorCodeOutOfMemory uint8 = 4
// The operation timed out before it could finish completely.
ErrorCodeTimeout uint8 = 5
// The operation is not valid in the socket's current state.
ErrorCodeInvalidState uint8 = 6
// A bind operation failed because the provided address is not an address that the `network` can bind to.
ErrorCodeAddressNotBindable uint8 = 7
// A bind operation failed because the provided address is already in use or because there are no ephemeral ports available.
ErrorCodeAddressInUse uint8 = 8
// The remote address is not reachable
ErrorCodeRemoteUnreachable uint8 = 9
// The TCP connection was forcefully rejected
ErrorCodeConnectionRefused uint8 = 10
// The TCP connection was reset.
ErrorCodeConnectionReset uint8 = 11
// A TCP connection was aborted.
ErrorCodeConnectionAborted uint8 = 12
// The size of a datagram sent to a UDP socket exceeded the maximum
// supported size.
ErrorCodeDatagramTooLarge uint8 = 13
)
// Error codes.
// 
// In theory, every API can return any error code.
// In practice, API's typically only return the errors documented per API
// combined with a couple of errors that are always possible:
// - `unknown`
// - `access-denied`
// - `not-supported`
// - `out-of-memory`
// 
// See each individual API for what the POSIX equivalents are. They sometimes differ per API.
type ErrorCode = uint8

const (
        // Similar to `AF_INET` in POSIX.
IpAddressFamilyIpv4 uint8 = 0
// Similar to `AF_INET6` in POSIX.
IpAddressFamilyIpv6 uint8 = 1
)
type IpAddressFamily = uint8
type Ipv4Address = wit_types.Tuple4[uint8, uint8, uint8, uint8]
type Ipv6Address = wit_types.Tuple8[uint16, uint16, uint16, uint16, uint16, uint16, uint16, uint16]

const (
IpAddressIpv4 uint8 = 0
IpAddressIpv6 uint8 = 1
)

type IpAddress struct {
        tag uint8
        value any
}

func (self IpAddress) Tag() uint8 {
        return self.tag
}

func (self IpAddress) Ipv4() wit_types.Tuple4[uint8, uint8, uint8, uint8] {
        if self.tag != IpAddressIpv4 {
                panic("tag mismatch")
        }
        return self.value.(wit_types.Tuple4[uint8, uint8, uint8, uint8])
}
func (self IpAddress) Ipv6() wit_types.Tuple8[uint16, uint16, uint16, uint16, uint16, uint16, uint16, uint16] {
        if self.tag != IpAddressIpv6 {
                panic("tag mismatch")
        }
        return self.value.(wit_types.Tuple8[uint16, uint16, uint16, uint16, uint16, uint16, uint16, uint16])
}

func MakeIpAddressIpv4(value wit_types.Tuple4[uint8, uint8, uint8, uint8]) IpAddress {
        return IpAddress{IpAddressIpv4, value}
}
func MakeIpAddressIpv6(value wit_types.Tuple8[uint16, uint16, uint16, uint16, uint16, uint16, uint16, uint16]) IpAddress {
        return IpAddress{IpAddressIpv6, value}
}



type Ipv4SocketAddress struct {
        // sin_port
Port uint16
// sin_addr
Address wit_types.Tuple4[uint8, uint8, uint8, uint8] 
}

type Ipv6SocketAddress struct {
        // sin6_port
Port uint16
// sin6_flowinfo
FlowInfo uint32
// sin6_addr
Address wit_types.Tuple8[uint16, uint16, uint16, uint16, uint16, uint16, uint16, uint16]
// sin6_scope_id
ScopeId uint32 
}

const (
IpSocketAddressIpv4 uint8 = 0
IpSocketAddressIpv6 uint8 = 1
)

type IpSocketAddress struct {
        tag uint8
        value any
}

func (self IpSocketAddress) Tag() uint8 {
        return self.tag
}

func (self IpSocketAddress) Ipv4() Ipv4SocketAddress {
        if self.tag != IpSocketAddressIpv4 {
                panic("tag mismatch")
        }
        return self.value.(Ipv4SocketAddress)
}
func (self IpSocketAddress) Ipv6() Ipv6SocketAddress {
        if self.tag != IpSocketAddressIpv6 {
                panic("tag mismatch")
        }
        return self.value.(Ipv6SocketAddress)
}

func MakeIpSocketAddressIpv4(value Ipv4SocketAddress) IpSocketAddress {
        return IpSocketAddress{IpSocketAddressIpv4, value}
}
func MakeIpSocketAddressIpv6(value Ipv6SocketAddress) IpSocketAddress {
        return IpSocketAddress{IpSocketAddressIpv6, value}
}



//go:wasmimport wasi:sockets/types@0.3.0-rc-2025-09-16 [resource-drop]tcp-socket
func resourceDropTcpSocket(handle int32)

// A TCP socket resource.
// 
// The socket can be in one of the following states:
// - `unbound`
// - `bound` (See note below)
// - `listening`
// - `connecting`
// - `connected`
// - `closed`
// See <https://github.com/WebAssembly/wasi-sockets/blob/main/TcpSocketOperationalSemantics-0.3.0-draft.md>
// for more information.
// 
// Note: Except where explicitly mentioned, whenever this documentation uses
// the term "bound" without backticks it actually means: in the `bound` state *or higher*.
// (i.e. `bound`, `listening`, `connecting` or `connected`)
// 
// In addition to the general error codes documented on the
// `types::error-code` type, TCP socket methods may always return
// `error(invalid-state)` when in the `closed` state.
type TcpSocket struct {
        handle *wit_runtime.Handle
}

func (self *TcpSocket) TakeHandle() int32 {
        return self.handle.Take()
}

func (self *TcpSocket) SetHandle(handle int32) {
        self.handle.Set(handle)
}

func (self *TcpSocket) Handle() int32 {
        return self.handle.Use()
}

func (self *TcpSocket) Drop() {
	handle := self.handle.TakeOrNil()
	if handle != 0 {
		resourceDropTcpSocket(handle)
	}
}

func TcpSocketFromOwnHandle(handleValue int32) *TcpSocket {
        handle := wit_runtime.MakeHandle(handleValue)
        value := &TcpSocket{handle}
        runtime.AddCleanup(value, func(_ int) {
                handleValue := handle.TakeOrNil()
                if handleValue != 0 {
                        resourceDropTcpSocket(handleValue)
                }
        }, 0)
        return value
}

func TcpSocketFromBorrowHandle(handleValue int32) *TcpSocket {
	return TcpSocketFromOwnHandle(handleValue)
}


//go:wasmimport wasi:sockets/types@0.3.0-rc-2025-09-16 [resource-drop]udp-socket
func resourceDropUdpSocket(handle int32)

// A UDP socket handle.
type UdpSocket struct {
        handle *wit_runtime.Handle
}

func (self *UdpSocket) TakeHandle() int32 {
        return self.handle.Take()
}

func (self *UdpSocket) SetHandle(handle int32) {
        self.handle.Set(handle)
}

func (self *UdpSocket) Handle() int32 {
        return self.handle.Use()
}

func (self *UdpSocket) Drop() {
	handle := self.handle.TakeOrNil()
	if handle != 0 {
		resourceDropUdpSocket(handle)
	}
}

func UdpSocketFromOwnHandle(handleValue int32) *UdpSocket {
        handle := wit_runtime.MakeHandle(handleValue)
        value := &UdpSocket{handle}
        runtime.AddCleanup(value, func(_ int) {
                handleValue := handle.TakeOrNil()
                if handleValue != 0 {
                        resourceDropUdpSocket(handleValue)
                }
        }, 0)
        return value
}

func UdpSocketFromBorrowHandle(handleValue int32) *UdpSocket {
	return UdpSocketFromOwnHandle(handleValue)
}


//go:wasmimport wasi:sockets/types@0.3.0-rc-2025-09-16 [static]tcp-socket.create
func wasm_import_static_tcp_socket_create(arg0 int32, arg1 uintptr) 

func TcpSocketCreate(addressFamily IpAddressFamily) wit_types.Result[*TcpSocket, ErrorCode] {
        pinner := &runtime.Pinner{}
defer pinner.Unpin()

        returnArea := uintptr(wit_runtime.Allocate(pinner, 8, 4))
        wasm_import_static_tcp_socket_create(int32(addressFamily), returnArea)
var result wit_types.Result[*TcpSocket, ErrorCode]
switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
case 0:
        
        result = wit_types.Ok[*TcpSocket, ErrorCode](TcpSocketFromOwnHandle(int32(uintptr(*(*int32)(unsafe.Add(unsafe.Pointer(returnArea), 4))))))
case 1:
        
        result = wit_types.Err[*TcpSocket, ErrorCode](uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4)))))
default:
        panic("unreachable")
}
result0 := result;
return result0

}

//go:wasmimport wasi:sockets/types@0.3.0-rc-2025-09-16 [method]tcp-socket.bind
func wasm_import_method_tcp_socket_bind(arg0 int32, arg1 int32, arg2 int32, arg3 int32, arg4 int32, arg5 int32, arg6 int32, arg7 int32, arg8 int32, arg9 int32, arg10 int32, arg11 int32, arg12 int32, arg13 uintptr) 

func (self *TcpSocket) Bind(localAddress IpSocketAddress) wit_types.Result[wit_types.Unit, ErrorCode] {
        pinner := &runtime.Pinner{}
defer pinner.Unpin()

        returnArea := uintptr(wit_runtime.Allocate(pinner, 2, 1))
        var variant int32
var variant0 int32
var variant1 int32
var variant2 int32
var variant3 int32
var variant4 int32
var variant5 int32
var variant6 int32
var variant7 int32
var variant8 int32
var variant9 int32
var variant10 int32
switch localAddress.Tag() {
case IpSocketAddressIpv4:
        payload := localAddress.Ipv4()
        
        variant = int32(0)
variant0 = int32((payload).Port)
variant1 = int32(((payload).Address).F0)
variant2 = int32(((payload).Address).F1)
variant3 = int32(((payload).Address).F2)
variant4 = int32(((payload).Address).F3)
variant5 = 0
variant6 = 0
variant7 = 0
variant8 = 0
variant9 = 0
variant10 = 0

case IpSocketAddressIpv6:
        payload := localAddress.Ipv6()
        
        variant = int32(1)
variant0 = int32((payload).Port)
variant1 = int32((payload).FlowInfo)
variant2 = int32(((payload).Address).F0)
variant3 = int32(((payload).Address).F1)
variant4 = int32(((payload).Address).F2)
variant5 = int32(((payload).Address).F3)
variant6 = int32(((payload).Address).F4)
variant7 = int32(((payload).Address).F5)
variant8 = int32(((payload).Address).F6)
variant9 = int32(((payload).Address).F7)
variant10 = int32((payload).ScopeId)

default:
        panic("unreachable")
}
wasm_import_method_tcp_socket_bind((self).Handle(), variant, variant0, variant1, variant2, variant3, variant4, variant5, variant6, variant7, variant8, variant9, variant10, returnArea)
var result wit_types.Result[wit_types.Unit, ErrorCode]
switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
case 0:
        
        result = wit_types.Ok[wit_types.Unit, ErrorCode](wit_types.Unit{})
case 1:
        
        result = wit_types.Err[wit_types.Unit, ErrorCode](uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 1)))))
default:
        panic("unreachable")
}
result11 := result;
return result11

}

//go:wasmimport wasi:sockets/types@0.3.0-rc-2025-09-16 [async-lower][method]tcp-socket.connect
func wasm_import_method_tcp_socket_connect(arg0 uintptr, arg1 uintptr) int32

func (self *TcpSocket) Connect(remoteAddress IpSocketAddress) wit_types.Result[wit_types.Unit, ErrorCode] {
        pinner := &runtime.Pinner{}
defer pinner.Unpin()

        returnArea := uintptr(wit_runtime.Allocate(pinner, 2, 1))
        params := wit_runtime.Allocate(pinner, 36, 4)
*(*int32)(unsafe.Add(unsafe.Pointer(unsafe.Add(unsafe.Pointer(params), 0)), 0)) = (self).Handle()

switch remoteAddress.Tag() {
case IpSocketAddressIpv4:
        payload := remoteAddress.Ipv4()
        *(*int8)(unsafe.Add(unsafe.Pointer(unsafe.Add(unsafe.Pointer(params), 4)), 0)) = int8(int32(0))
*(*int16)(unsafe.Add(unsafe.Pointer(unsafe.Add(unsafe.Pointer(params), 4)), 4)) = int16(int32((payload).Port))
*(*int8)(unsafe.Add(unsafe.Pointer(unsafe.Add(unsafe.Pointer(params), 4)), 6)) = int8(int32(((payload).Address).F0))
*(*int8)(unsafe.Add(unsafe.Pointer(unsafe.Add(unsafe.Pointer(params), 4)), 7)) = int8(int32(((payload).Address).F1))
*(*int8)(unsafe.Add(unsafe.Pointer(unsafe.Add(unsafe.Pointer(params), 4)), 8)) = int8(int32(((payload).Address).F2))
*(*int8)(unsafe.Add(unsafe.Pointer(unsafe.Add(unsafe.Pointer(params), 4)), 9)) = int8(int32(((payload).Address).F3))

        

case IpSocketAddressIpv6:
        payload := remoteAddress.Ipv6()
        *(*int8)(unsafe.Add(unsafe.Pointer(unsafe.Add(unsafe.Pointer(params), 4)), 0)) = int8(int32(1))
*(*int16)(unsafe.Add(unsafe.Pointer(unsafe.Add(unsafe.Pointer(params), 4)), 4)) = int16(int32((payload).Port))
*(*int32)(unsafe.Add(unsafe.Pointer(unsafe.Add(unsafe.Pointer(params), 4)), 8)) = int32((payload).FlowInfo)
*(*int16)(unsafe.Add(unsafe.Pointer(unsafe.Add(unsafe.Pointer(params), 4)), 12)) = int16(int32(((payload).Address).F0))
*(*int16)(unsafe.Add(unsafe.Pointer(unsafe.Add(unsafe.Pointer(params), 4)), 14)) = int16(int32(((payload).Address).F1))
*(*int16)(unsafe.Add(unsafe.Pointer(unsafe.Add(unsafe.Pointer(params), 4)), 16)) = int16(int32(((payload).Address).F2))
*(*int16)(unsafe.Add(unsafe.Pointer(unsafe.Add(unsafe.Pointer(params), 4)), 18)) = int16(int32(((payload).Address).F3))
*(*int16)(unsafe.Add(unsafe.Pointer(unsafe.Add(unsafe.Pointer(params), 4)), 20)) = int16(int32(((payload).Address).F4))
*(*int16)(unsafe.Add(unsafe.Pointer(unsafe.Add(unsafe.Pointer(params), 4)), 22)) = int16(int32(((payload).Address).F5))
*(*int16)(unsafe.Add(unsafe.Pointer(unsafe.Add(unsafe.Pointer(params), 4)), 24)) = int16(int32(((payload).Address).F6))
*(*int16)(unsafe.Add(unsafe.Pointer(unsafe.Add(unsafe.Pointer(params), 4)), 26)) = int16(int32(((payload).Address).F7))
*(*int32)(unsafe.Add(unsafe.Pointer(unsafe.Add(unsafe.Pointer(params), 4)), 28)) = int32((payload).ScopeId)

        

default:
        panic("unreachable")
}

wit_async.SubtaskWait(uint32(wasm_import_method_tcp_socket_connect(uintptr(params), returnArea)))
var result wit_types.Result[wit_types.Unit, ErrorCode]
switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
case 0:
        
        result = wit_types.Ok[wit_types.Unit, ErrorCode](wit_types.Unit{})
case 1:
        
        result = wit_types.Err[wit_types.Unit, ErrorCode](uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 1)))))
default:
        panic("unreachable")
}

return result

}

//go:wasmimport wasi:sockets/types@0.3.0-rc-2025-09-16 [method]tcp-socket.listen
func wasm_import_method_tcp_socket_listen(arg0 int32, arg1 uintptr) 

func (self *TcpSocket) Listen() wit_types.Result[*wit_types.StreamReader[*TcpSocket], ErrorCode] {
        pinner := &runtime.Pinner{}
defer pinner.Unpin()

        returnArea := uintptr(wit_runtime.Allocate(pinner, 8, 4))
        wasm_import_method_tcp_socket_listen((self).Handle(), returnArea)
var result wit_types.Result[*wit_types.StreamReader[*TcpSocket], ErrorCode]
switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
case 0:
        
        result = wit_types.Ok[*wit_types.StreamReader[*TcpSocket], ErrorCode](LiftStreamTcpSocket(*(*int32)(unsafe.Add(unsafe.Pointer(returnArea), 4))))
case 1:
        
        result = wit_types.Err[*wit_types.StreamReader[*TcpSocket], ErrorCode](uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4)))))
default:
        panic("unreachable")
}
result0 := result;
return result0

}

//go:wasmimport wasi:sockets/types@0.3.0-rc-2025-09-16 [async-lower][method]tcp-socket.send
func wasm_import_method_tcp_socket_send(arg0 int32, arg1 int32, arg2 uintptr) int32

func (self *TcpSocket) Send(data *wit_types.StreamReader[uint8]) wit_types.Result[wit_types.Unit, ErrorCode] {
        pinner := &runtime.Pinner{}
defer pinner.Unpin()

        returnArea := uintptr(wit_runtime.Allocate(pinner, 2, 1))
        
wit_async.SubtaskWait(uint32(wasm_import_method_tcp_socket_send((self).Handle(), (data).TakeHandle(), returnArea)))
var result wit_types.Result[wit_types.Unit, ErrorCode]
switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
case 0:
        
        result = wit_types.Ok[wit_types.Unit, ErrorCode](wit_types.Unit{})
case 1:
        
        result = wit_types.Err[wit_types.Unit, ErrorCode](uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 1)))))
default:
        panic("unreachable")
}

return result

}

//go:wasmimport wasi:sockets/types@0.3.0-rc-2025-09-16 [method]tcp-socket.receive
func wasm_import_method_tcp_socket_receive(arg0 int32, arg1 uintptr) 

func (self *TcpSocket) Receive() (*wit_types.StreamReader[uint8], *wit_types.FutureReader[wit_types.Result[wit_types.Unit, ErrorCode]]) {
        pinner := &runtime.Pinner{}
defer pinner.Unpin()

        returnArea := uintptr(wit_runtime.Allocate(pinner, 8, 4))
        wasm_import_method_tcp_socket_receive((self).Handle(), returnArea)
result := wit_types.Tuple2[*wit_types.StreamReader[uint8], *wit_types.FutureReader[wit_types.Result[wit_types.Unit, ErrorCode]]]{LiftStreamU8(*(*int32)(unsafe.Add(unsafe.Pointer(returnArea), 0))), LiftFutureResultUnitErrorCode(*(*int32)(unsafe.Add(unsafe.Pointer(returnArea), 4)))};
tuple := result
return tuple.F0, tuple.F1

}

//go:wasmimport wasi:sockets/types@0.3.0-rc-2025-09-16 [method]tcp-socket.get-local-address
func wasm_import_method_tcp_socket_get_local_address(arg0 int32, arg1 uintptr) 

func (self *TcpSocket) GetLocalAddress() wit_types.Result[IpSocketAddress, ErrorCode] {
        pinner := &runtime.Pinner{}
defer pinner.Unpin()

        returnArea := uintptr(wit_runtime.Allocate(pinner, 36, 4))
        wasm_import_method_tcp_socket_get_local_address((self).Handle(), returnArea)
var result wit_types.Result[IpSocketAddress, ErrorCode]
switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
case 0:
        var variant IpSocketAddress
switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))) {
case 0:
        
        variant = MakeIpSocketAddressIpv4(Ipv4SocketAddress{uint16(uint16(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 8)))), wit_types.Tuple4[uint8, uint8, uint8, uint8]{uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 10)))), uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 11)))), uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 12)))), uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 13))))}})

case 1:
        
        variant = MakeIpSocketAddressIpv6(Ipv6SocketAddress{uint16(uint16(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 8)))), uint32(*(*int32)(unsafe.Add(unsafe.Pointer(returnArea), 12))), wit_types.Tuple8[uint16, uint16, uint16, uint16, uint16, uint16, uint16, uint16]{uint16(uint16(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16)))), uint16(uint16(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 18)))), uint16(uint16(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 20)))), uint16(uint16(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 22)))), uint16(uint16(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 24)))), uint16(uint16(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 26)))), uint16(uint16(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 28)))), uint16(uint16(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 30))))}, uint32(*(*int32)(unsafe.Add(unsafe.Pointer(returnArea), 32)))})

default:
        panic("unreachable")
}

        result = wit_types.Ok[IpSocketAddress, ErrorCode](variant)
case 1:
        
        result = wit_types.Err[IpSocketAddress, ErrorCode](uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4)))))
default:
        panic("unreachable")
}
result0 := result;
return result0

}

//go:wasmimport wasi:sockets/types@0.3.0-rc-2025-09-16 [method]tcp-socket.get-remote-address
func wasm_import_method_tcp_socket_get_remote_address(arg0 int32, arg1 uintptr) 

func (self *TcpSocket) GetRemoteAddress() wit_types.Result[IpSocketAddress, ErrorCode] {
        pinner := &runtime.Pinner{}
defer pinner.Unpin()

        returnArea := uintptr(wit_runtime.Allocate(pinner, 36, 4))
        wasm_import_method_tcp_socket_get_remote_address((self).Handle(), returnArea)
var result wit_types.Result[IpSocketAddress, ErrorCode]
switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
case 0:
        var variant IpSocketAddress
switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))) {
case 0:
        
        variant = MakeIpSocketAddressIpv4(Ipv4SocketAddress{uint16(uint16(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 8)))), wit_types.Tuple4[uint8, uint8, uint8, uint8]{uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 10)))), uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 11)))), uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 12)))), uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 13))))}})

case 1:
        
        variant = MakeIpSocketAddressIpv6(Ipv6SocketAddress{uint16(uint16(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 8)))), uint32(*(*int32)(unsafe.Add(unsafe.Pointer(returnArea), 12))), wit_types.Tuple8[uint16, uint16, uint16, uint16, uint16, uint16, uint16, uint16]{uint16(uint16(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16)))), uint16(uint16(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 18)))), uint16(uint16(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 20)))), uint16(uint16(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 22)))), uint16(uint16(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 24)))), uint16(uint16(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 26)))), uint16(uint16(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 28)))), uint16(uint16(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 30))))}, uint32(*(*int32)(unsafe.Add(unsafe.Pointer(returnArea), 32)))})

default:
        panic("unreachable")
}

        result = wit_types.Ok[IpSocketAddress, ErrorCode](variant)
case 1:
        
        result = wit_types.Err[IpSocketAddress, ErrorCode](uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4)))))
default:
        panic("unreachable")
}
result0 := result;
return result0

}

//go:wasmimport wasi:sockets/types@0.3.0-rc-2025-09-16 [method]tcp-socket.get-is-listening
func wasm_import_method_tcp_socket_get_is_listening(arg0 int32) int32

func (self *TcpSocket) GetIsListening() bool {
        
        
        result := wasm_import_method_tcp_socket_get_is_listening((self).Handle())
return (result != 0)

}

//go:wasmimport wasi:sockets/types@0.3.0-rc-2025-09-16 [method]tcp-socket.get-address-family
func wasm_import_method_tcp_socket_get_address_family(arg0 int32) int32

func (self *TcpSocket) GetAddressFamily() IpAddressFamily {
        
        
        result := wasm_import_method_tcp_socket_get_address_family((self).Handle())
return uint8(result)

}

//go:wasmimport wasi:sockets/types@0.3.0-rc-2025-09-16 [method]tcp-socket.set-listen-backlog-size
func wasm_import_method_tcp_socket_set_listen_backlog_size(arg0 int32, arg1 int64, arg2 uintptr) 

func (self *TcpSocket) SetListenBacklogSize(value uint64) wit_types.Result[wit_types.Unit, ErrorCode] {
        pinner := &runtime.Pinner{}
defer pinner.Unpin()

        returnArea := uintptr(wit_runtime.Allocate(pinner, 2, 1))
        wasm_import_method_tcp_socket_set_listen_backlog_size((self).Handle(), int64(value), returnArea)
var result wit_types.Result[wit_types.Unit, ErrorCode]
switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
case 0:
        
        result = wit_types.Ok[wit_types.Unit, ErrorCode](wit_types.Unit{})
case 1:
        
        result = wit_types.Err[wit_types.Unit, ErrorCode](uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 1)))))
default:
        panic("unreachable")
}
result0 := result;
return result0

}

//go:wasmimport wasi:sockets/types@0.3.0-rc-2025-09-16 [method]tcp-socket.get-keep-alive-enabled
func wasm_import_method_tcp_socket_get_keep_alive_enabled(arg0 int32, arg1 uintptr) 

func (self *TcpSocket) GetKeepAliveEnabled() wit_types.Result[bool, ErrorCode] {
        pinner := &runtime.Pinner{}
defer pinner.Unpin()

        returnArea := uintptr(wit_runtime.Allocate(pinner, 2, 1))
        wasm_import_method_tcp_socket_get_keep_alive_enabled((self).Handle(), returnArea)
var result wit_types.Result[bool, ErrorCode]
switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
case 0:
        
        result = wit_types.Ok[bool, ErrorCode]((uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 1))) != 0))
case 1:
        
        result = wit_types.Err[bool, ErrorCode](uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 1)))))
default:
        panic("unreachable")
}
result0 := result;
return result0

}

//go:wasmimport wasi:sockets/types@0.3.0-rc-2025-09-16 [method]tcp-socket.set-keep-alive-enabled
func wasm_import_method_tcp_socket_set_keep_alive_enabled(arg0 int32, arg1 int32, arg2 uintptr) 

func (self *TcpSocket) SetKeepAliveEnabled(value bool) wit_types.Result[wit_types.Unit, ErrorCode] {
        pinner := &runtime.Pinner{}
defer pinner.Unpin()

        returnArea := uintptr(wit_runtime.Allocate(pinner, 2, 1))
        var result int32
if value {
        result = 1
} else {
        result = 0
}
wasm_import_method_tcp_socket_set_keep_alive_enabled((self).Handle(), result, returnArea)
var result0 wit_types.Result[wit_types.Unit, ErrorCode]
switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
case 0:
        
        result0 = wit_types.Ok[wit_types.Unit, ErrorCode](wit_types.Unit{})
case 1:
        
        result0 = wit_types.Err[wit_types.Unit, ErrorCode](uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 1)))))
default:
        panic("unreachable")
}
result1 := result0;
return result1

}

//go:wasmimport wasi:sockets/types@0.3.0-rc-2025-09-16 [method]tcp-socket.get-keep-alive-idle-time
func wasm_import_method_tcp_socket_get_keep_alive_idle_time(arg0 int32, arg1 uintptr) 

func (self *TcpSocket) GetKeepAliveIdleTime() wit_types.Result[uint64, ErrorCode] {
        pinner := &runtime.Pinner{}
defer pinner.Unpin()

        returnArea := uintptr(wit_runtime.Allocate(pinner, 16, 8))
        wasm_import_method_tcp_socket_get_keep_alive_idle_time((self).Handle(), returnArea)
var result wit_types.Result[uint64, ErrorCode]
switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
case 0:
        
        result = wit_types.Ok[uint64, ErrorCode](uint64(*(*int64)(unsafe.Add(unsafe.Pointer(returnArea), 8))))
case 1:
        
        result = wit_types.Err[uint64, ErrorCode](uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 8)))))
default:
        panic("unreachable")
}
result0 := result;
return result0

}

//go:wasmimport wasi:sockets/types@0.3.0-rc-2025-09-16 [method]tcp-socket.set-keep-alive-idle-time
func wasm_import_method_tcp_socket_set_keep_alive_idle_time(arg0 int32, arg1 int64, arg2 uintptr) 

func (self *TcpSocket) SetKeepAliveIdleTime(value uint64) wit_types.Result[wit_types.Unit, ErrorCode] {
        pinner := &runtime.Pinner{}
defer pinner.Unpin()

        returnArea := uintptr(wit_runtime.Allocate(pinner, 2, 1))
        wasm_import_method_tcp_socket_set_keep_alive_idle_time((self).Handle(), int64(value), returnArea)
var result wit_types.Result[wit_types.Unit, ErrorCode]
switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
case 0:
        
        result = wit_types.Ok[wit_types.Unit, ErrorCode](wit_types.Unit{})
case 1:
        
        result = wit_types.Err[wit_types.Unit, ErrorCode](uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 1)))))
default:
        panic("unreachable")
}
result0 := result;
return result0

}

//go:wasmimport wasi:sockets/types@0.3.0-rc-2025-09-16 [method]tcp-socket.get-keep-alive-interval
func wasm_import_method_tcp_socket_get_keep_alive_interval(arg0 int32, arg1 uintptr) 

func (self *TcpSocket) GetKeepAliveInterval() wit_types.Result[uint64, ErrorCode] {
        pinner := &runtime.Pinner{}
defer pinner.Unpin()

        returnArea := uintptr(wit_runtime.Allocate(pinner, 16, 8))
        wasm_import_method_tcp_socket_get_keep_alive_interval((self).Handle(), returnArea)
var result wit_types.Result[uint64, ErrorCode]
switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
case 0:
        
        result = wit_types.Ok[uint64, ErrorCode](uint64(*(*int64)(unsafe.Add(unsafe.Pointer(returnArea), 8))))
case 1:
        
        result = wit_types.Err[uint64, ErrorCode](uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 8)))))
default:
        panic("unreachable")
}
result0 := result;
return result0

}

//go:wasmimport wasi:sockets/types@0.3.0-rc-2025-09-16 [method]tcp-socket.set-keep-alive-interval
func wasm_import_method_tcp_socket_set_keep_alive_interval(arg0 int32, arg1 int64, arg2 uintptr) 

func (self *TcpSocket) SetKeepAliveInterval(value uint64) wit_types.Result[wit_types.Unit, ErrorCode] {
        pinner := &runtime.Pinner{}
defer pinner.Unpin()

        returnArea := uintptr(wit_runtime.Allocate(pinner, 2, 1))
        wasm_import_method_tcp_socket_set_keep_alive_interval((self).Handle(), int64(value), returnArea)
var result wit_types.Result[wit_types.Unit, ErrorCode]
switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
case 0:
        
        result = wit_types.Ok[wit_types.Unit, ErrorCode](wit_types.Unit{})
case 1:
        
        result = wit_types.Err[wit_types.Unit, ErrorCode](uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 1)))))
default:
        panic("unreachable")
}
result0 := result;
return result0

}

//go:wasmimport wasi:sockets/types@0.3.0-rc-2025-09-16 [method]tcp-socket.get-keep-alive-count
func wasm_import_method_tcp_socket_get_keep_alive_count(arg0 int32, arg1 uintptr) 

func (self *TcpSocket) GetKeepAliveCount() wit_types.Result[uint32, ErrorCode] {
        pinner := &runtime.Pinner{}
defer pinner.Unpin()

        returnArea := uintptr(wit_runtime.Allocate(pinner, 8, 4))
        wasm_import_method_tcp_socket_get_keep_alive_count((self).Handle(), returnArea)
var result wit_types.Result[uint32, ErrorCode]
switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
case 0:
        
        result = wit_types.Ok[uint32, ErrorCode](uint32(*(*int32)(unsafe.Add(unsafe.Pointer(returnArea), 4))))
case 1:
        
        result = wit_types.Err[uint32, ErrorCode](uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4)))))
default:
        panic("unreachable")
}
result0 := result;
return result0

}

//go:wasmimport wasi:sockets/types@0.3.0-rc-2025-09-16 [method]tcp-socket.set-keep-alive-count
func wasm_import_method_tcp_socket_set_keep_alive_count(arg0 int32, arg1 int32, arg2 uintptr) 

func (self *TcpSocket) SetKeepAliveCount(value uint32) wit_types.Result[wit_types.Unit, ErrorCode] {
        pinner := &runtime.Pinner{}
defer pinner.Unpin()

        returnArea := uintptr(wit_runtime.Allocate(pinner, 2, 1))
        wasm_import_method_tcp_socket_set_keep_alive_count((self).Handle(), int32(value), returnArea)
var result wit_types.Result[wit_types.Unit, ErrorCode]
switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
case 0:
        
        result = wit_types.Ok[wit_types.Unit, ErrorCode](wit_types.Unit{})
case 1:
        
        result = wit_types.Err[wit_types.Unit, ErrorCode](uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 1)))))
default:
        panic("unreachable")
}
result0 := result;
return result0

}

//go:wasmimport wasi:sockets/types@0.3.0-rc-2025-09-16 [method]tcp-socket.get-hop-limit
func wasm_import_method_tcp_socket_get_hop_limit(arg0 int32, arg1 uintptr) 

func (self *TcpSocket) GetHopLimit() wit_types.Result[uint8, ErrorCode] {
        pinner := &runtime.Pinner{}
defer pinner.Unpin()

        returnArea := uintptr(wit_runtime.Allocate(pinner, 2, 1))
        wasm_import_method_tcp_socket_get_hop_limit((self).Handle(), returnArea)
var result wit_types.Result[uint8, ErrorCode]
switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
case 0:
        
        result = wit_types.Ok[uint8, ErrorCode](uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 1)))))
case 1:
        
        result = wit_types.Err[uint8, ErrorCode](uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 1)))))
default:
        panic("unreachable")
}
result0 := result;
return result0

}

//go:wasmimport wasi:sockets/types@0.3.0-rc-2025-09-16 [method]tcp-socket.set-hop-limit
func wasm_import_method_tcp_socket_set_hop_limit(arg0 int32, arg1 int32, arg2 uintptr) 

func (self *TcpSocket) SetHopLimit(value uint8) wit_types.Result[wit_types.Unit, ErrorCode] {
        pinner := &runtime.Pinner{}
defer pinner.Unpin()

        returnArea := uintptr(wit_runtime.Allocate(pinner, 2, 1))
        wasm_import_method_tcp_socket_set_hop_limit((self).Handle(), int32(value), returnArea)
var result wit_types.Result[wit_types.Unit, ErrorCode]
switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
case 0:
        
        result = wit_types.Ok[wit_types.Unit, ErrorCode](wit_types.Unit{})
case 1:
        
        result = wit_types.Err[wit_types.Unit, ErrorCode](uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 1)))))
default:
        panic("unreachable")
}
result0 := result;
return result0

}

//go:wasmimport wasi:sockets/types@0.3.0-rc-2025-09-16 [method]tcp-socket.get-receive-buffer-size
func wasm_import_method_tcp_socket_get_receive_buffer_size(arg0 int32, arg1 uintptr) 

func (self *TcpSocket) GetReceiveBufferSize() wit_types.Result[uint64, ErrorCode] {
        pinner := &runtime.Pinner{}
defer pinner.Unpin()

        returnArea := uintptr(wit_runtime.Allocate(pinner, 16, 8))
        wasm_import_method_tcp_socket_get_receive_buffer_size((self).Handle(), returnArea)
var result wit_types.Result[uint64, ErrorCode]
switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
case 0:
        
        result = wit_types.Ok[uint64, ErrorCode](uint64(*(*int64)(unsafe.Add(unsafe.Pointer(returnArea), 8))))
case 1:
        
        result = wit_types.Err[uint64, ErrorCode](uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 8)))))
default:
        panic("unreachable")
}
result0 := result;
return result0

}

//go:wasmimport wasi:sockets/types@0.3.0-rc-2025-09-16 [method]tcp-socket.set-receive-buffer-size
func wasm_import_method_tcp_socket_set_receive_buffer_size(arg0 int32, arg1 int64, arg2 uintptr) 

func (self *TcpSocket) SetReceiveBufferSize(value uint64) wit_types.Result[wit_types.Unit, ErrorCode] {
        pinner := &runtime.Pinner{}
defer pinner.Unpin()

        returnArea := uintptr(wit_runtime.Allocate(pinner, 2, 1))
        wasm_import_method_tcp_socket_set_receive_buffer_size((self).Handle(), int64(value), returnArea)
var result wit_types.Result[wit_types.Unit, ErrorCode]
switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
case 0:
        
        result = wit_types.Ok[wit_types.Unit, ErrorCode](wit_types.Unit{})
case 1:
        
        result = wit_types.Err[wit_types.Unit, ErrorCode](uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 1)))))
default:
        panic("unreachable")
}
result0 := result;
return result0

}

//go:wasmimport wasi:sockets/types@0.3.0-rc-2025-09-16 [method]tcp-socket.get-send-buffer-size
func wasm_import_method_tcp_socket_get_send_buffer_size(arg0 int32, arg1 uintptr) 

func (self *TcpSocket) GetSendBufferSize() wit_types.Result[uint64, ErrorCode] {
        pinner := &runtime.Pinner{}
defer pinner.Unpin()

        returnArea := uintptr(wit_runtime.Allocate(pinner, 16, 8))
        wasm_import_method_tcp_socket_get_send_buffer_size((self).Handle(), returnArea)
var result wit_types.Result[uint64, ErrorCode]
switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
case 0:
        
        result = wit_types.Ok[uint64, ErrorCode](uint64(*(*int64)(unsafe.Add(unsafe.Pointer(returnArea), 8))))
case 1:
        
        result = wit_types.Err[uint64, ErrorCode](uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 8)))))
default:
        panic("unreachable")
}
result0 := result;
return result0

}

//go:wasmimport wasi:sockets/types@0.3.0-rc-2025-09-16 [method]tcp-socket.set-send-buffer-size
func wasm_import_method_tcp_socket_set_send_buffer_size(arg0 int32, arg1 int64, arg2 uintptr) 

func (self *TcpSocket) SetSendBufferSize(value uint64) wit_types.Result[wit_types.Unit, ErrorCode] {
        pinner := &runtime.Pinner{}
defer pinner.Unpin()

        returnArea := uintptr(wit_runtime.Allocate(pinner, 2, 1))
        wasm_import_method_tcp_socket_set_send_buffer_size((self).Handle(), int64(value), returnArea)
var result wit_types.Result[wit_types.Unit, ErrorCode]
switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
case 0:
        
        result = wit_types.Ok[wit_types.Unit, ErrorCode](wit_types.Unit{})
case 1:
        
        result = wit_types.Err[wit_types.Unit, ErrorCode](uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 1)))))
default:
        panic("unreachable")
}
result0 := result;
return result0

}

//go:wasmimport wasi:sockets/types@0.3.0-rc-2025-09-16 [static]udp-socket.create
func wasm_import_static_udp_socket_create(arg0 int32, arg1 uintptr) 

func UdpSocketCreate(addressFamily IpAddressFamily) wit_types.Result[*UdpSocket, ErrorCode] {
        pinner := &runtime.Pinner{}
defer pinner.Unpin()

        returnArea := uintptr(wit_runtime.Allocate(pinner, 8, 4))
        wasm_import_static_udp_socket_create(int32(addressFamily), returnArea)
var result wit_types.Result[*UdpSocket, ErrorCode]
switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
case 0:
        
        result = wit_types.Ok[*UdpSocket, ErrorCode](UdpSocketFromOwnHandle(int32(uintptr(*(*int32)(unsafe.Add(unsafe.Pointer(returnArea), 4))))))
case 1:
        
        result = wit_types.Err[*UdpSocket, ErrorCode](uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4)))))
default:
        panic("unreachable")
}
result0 := result;
return result0

}

//go:wasmimport wasi:sockets/types@0.3.0-rc-2025-09-16 [method]udp-socket.bind
func wasm_import_method_udp_socket_bind(arg0 int32, arg1 int32, arg2 int32, arg3 int32, arg4 int32, arg5 int32, arg6 int32, arg7 int32, arg8 int32, arg9 int32, arg10 int32, arg11 int32, arg12 int32, arg13 uintptr) 

func (self *UdpSocket) Bind(localAddress IpSocketAddress) wit_types.Result[wit_types.Unit, ErrorCode] {
        pinner := &runtime.Pinner{}
defer pinner.Unpin()

        returnArea := uintptr(wit_runtime.Allocate(pinner, 2, 1))
        var variant int32
var variant0 int32
var variant1 int32
var variant2 int32
var variant3 int32
var variant4 int32
var variant5 int32
var variant6 int32
var variant7 int32
var variant8 int32
var variant9 int32
var variant10 int32
switch localAddress.Tag() {
case IpSocketAddressIpv4:
        payload := localAddress.Ipv4()
        
        variant = int32(0)
variant0 = int32((payload).Port)
variant1 = int32(((payload).Address).F0)
variant2 = int32(((payload).Address).F1)
variant3 = int32(((payload).Address).F2)
variant4 = int32(((payload).Address).F3)
variant5 = 0
variant6 = 0
variant7 = 0
variant8 = 0
variant9 = 0
variant10 = 0

case IpSocketAddressIpv6:
        payload := localAddress.Ipv6()
        
        variant = int32(1)
variant0 = int32((payload).Port)
variant1 = int32((payload).FlowInfo)
variant2 = int32(((payload).Address).F0)
variant3 = int32(((payload).Address).F1)
variant4 = int32(((payload).Address).F2)
variant5 = int32(((payload).Address).F3)
variant6 = int32(((payload).Address).F4)
variant7 = int32(((payload).Address).F5)
variant8 = int32(((payload).Address).F6)
variant9 = int32(((payload).Address).F7)
variant10 = int32((payload).ScopeId)

default:
        panic("unreachable")
}
wasm_import_method_udp_socket_bind((self).Handle(), variant, variant0, variant1, variant2, variant3, variant4, variant5, variant6, variant7, variant8, variant9, variant10, returnArea)
var result wit_types.Result[wit_types.Unit, ErrorCode]
switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
case 0:
        
        result = wit_types.Ok[wit_types.Unit, ErrorCode](wit_types.Unit{})
case 1:
        
        result = wit_types.Err[wit_types.Unit, ErrorCode](uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 1)))))
default:
        panic("unreachable")
}
result11 := result;
return result11

}

//go:wasmimport wasi:sockets/types@0.3.0-rc-2025-09-16 [method]udp-socket.connect
func wasm_import_method_udp_socket_connect(arg0 int32, arg1 int32, arg2 int32, arg3 int32, arg4 int32, arg5 int32, arg6 int32, arg7 int32, arg8 int32, arg9 int32, arg10 int32, arg11 int32, arg12 int32, arg13 uintptr) 

func (self *UdpSocket) Connect(remoteAddress IpSocketAddress) wit_types.Result[wit_types.Unit, ErrorCode] {
        pinner := &runtime.Pinner{}
defer pinner.Unpin()

        returnArea := uintptr(wit_runtime.Allocate(pinner, 2, 1))
        var variant int32
var variant0 int32
var variant1 int32
var variant2 int32
var variant3 int32
var variant4 int32
var variant5 int32
var variant6 int32
var variant7 int32
var variant8 int32
var variant9 int32
var variant10 int32
switch remoteAddress.Tag() {
case IpSocketAddressIpv4:
        payload := remoteAddress.Ipv4()
        
        variant = int32(0)
variant0 = int32((payload).Port)
variant1 = int32(((payload).Address).F0)
variant2 = int32(((payload).Address).F1)
variant3 = int32(((payload).Address).F2)
variant4 = int32(((payload).Address).F3)
variant5 = 0
variant6 = 0
variant7 = 0
variant8 = 0
variant9 = 0
variant10 = 0

case IpSocketAddressIpv6:
        payload := remoteAddress.Ipv6()
        
        variant = int32(1)
variant0 = int32((payload).Port)
variant1 = int32((payload).FlowInfo)
variant2 = int32(((payload).Address).F0)
variant3 = int32(((payload).Address).F1)
variant4 = int32(((payload).Address).F2)
variant5 = int32(((payload).Address).F3)
variant6 = int32(((payload).Address).F4)
variant7 = int32(((payload).Address).F5)
variant8 = int32(((payload).Address).F6)
variant9 = int32(((payload).Address).F7)
variant10 = int32((payload).ScopeId)

default:
        panic("unreachable")
}
wasm_import_method_udp_socket_connect((self).Handle(), variant, variant0, variant1, variant2, variant3, variant4, variant5, variant6, variant7, variant8, variant9, variant10, returnArea)
var result wit_types.Result[wit_types.Unit, ErrorCode]
switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
case 0:
        
        result = wit_types.Ok[wit_types.Unit, ErrorCode](wit_types.Unit{})
case 1:
        
        result = wit_types.Err[wit_types.Unit, ErrorCode](uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 1)))))
default:
        panic("unreachable")
}
result11 := result;
return result11

}

//go:wasmimport wasi:sockets/types@0.3.0-rc-2025-09-16 [method]udp-socket.disconnect
func wasm_import_method_udp_socket_disconnect(arg0 int32, arg1 uintptr) 

func (self *UdpSocket) Disconnect() wit_types.Result[wit_types.Unit, ErrorCode] {
        pinner := &runtime.Pinner{}
defer pinner.Unpin()

        returnArea := uintptr(wit_runtime.Allocate(pinner, 2, 1))
        wasm_import_method_udp_socket_disconnect((self).Handle(), returnArea)
var result wit_types.Result[wit_types.Unit, ErrorCode]
switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
case 0:
        
        result = wit_types.Ok[wit_types.Unit, ErrorCode](wit_types.Unit{})
case 1:
        
        result = wit_types.Err[wit_types.Unit, ErrorCode](uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 1)))))
default:
        panic("unreachable")
}
result0 := result;
return result0

}

//go:wasmimport wasi:sockets/types@0.3.0-rc-2025-09-16 [async-lower][method]udp-socket.send
func wasm_import_method_udp_socket_send(arg0 uintptr, arg1 uintptr) int32

func (self *UdpSocket) Send(data []uint8, remoteAddress wit_types.Option[IpSocketAddress]) wit_types.Result[wit_types.Unit, ErrorCode] {
        pinner := &runtime.Pinner{}
defer pinner.Unpin()

        returnArea := uintptr(wit_runtime.Allocate(pinner, 2, 1))
        params := wit_runtime.Allocate(pinner, (32+4*4), 4)
*(*int32)(unsafe.Add(unsafe.Pointer(unsafe.Add(unsafe.Pointer(params), 0)), 0)) = (self).Handle()
data0 := unsafe.Pointer(unsafe.SliceData(data))
pinner.Pin(data0)
*(*uint32)(unsafe.Add(unsafe.Pointer(unsafe.Add(unsafe.Pointer(params), 4)), 4)) = uint32(uint32(len(data)))
*(*uint32)(unsafe.Add(unsafe.Pointer(unsafe.Add(unsafe.Pointer(params), 4)), 0)) = uint32(uintptr(uintptr(data0)))

switch remoteAddress.Tag() {
case wit_types.OptionNone:
        *(*int8)(unsafe.Add(unsafe.Pointer(unsafe.Add(unsafe.Pointer(params), (3*4))), 0)) = int8(int32(0))

        
case wit_types.OptionSome:
        payload := remoteAddress.Some()
        *(*int8)(unsafe.Add(unsafe.Pointer(unsafe.Add(unsafe.Pointer(params), (3*4))), 0)) = int8(int32(1))

switch payload.Tag() {
case IpSocketAddressIpv4:
        payload := payload.Ipv4()
        *(*int8)(unsafe.Add(unsafe.Pointer(unsafe.Add(unsafe.Pointer(params), (3*4))), 4)) = int8(int32(0))
*(*int16)(unsafe.Add(unsafe.Pointer(unsafe.Add(unsafe.Pointer(params), (3*4))), 8)) = int16(int32((payload).Port))
*(*int8)(unsafe.Add(unsafe.Pointer(unsafe.Add(unsafe.Pointer(params), (3*4))), 10)) = int8(int32(((payload).Address).F0))
*(*int8)(unsafe.Add(unsafe.Pointer(unsafe.Add(unsafe.Pointer(params), (3*4))), 11)) = int8(int32(((payload).Address).F1))
*(*int8)(unsafe.Add(unsafe.Pointer(unsafe.Add(unsafe.Pointer(params), (3*4))), 12)) = int8(int32(((payload).Address).F2))
*(*int8)(unsafe.Add(unsafe.Pointer(unsafe.Add(unsafe.Pointer(params), (3*4))), 13)) = int8(int32(((payload).Address).F3))

        

case IpSocketAddressIpv6:
        payload := payload.Ipv6()
        *(*int8)(unsafe.Add(unsafe.Pointer(unsafe.Add(unsafe.Pointer(params), (3*4))), 4)) = int8(int32(1))
*(*int16)(unsafe.Add(unsafe.Pointer(unsafe.Add(unsafe.Pointer(params), (3*4))), 8)) = int16(int32((payload).Port))
*(*int32)(unsafe.Add(unsafe.Pointer(unsafe.Add(unsafe.Pointer(params), (3*4))), 12)) = int32((payload).FlowInfo)
*(*int16)(unsafe.Add(unsafe.Pointer(unsafe.Add(unsafe.Pointer(params), (3*4))), 16)) = int16(int32(((payload).Address).F0))
*(*int16)(unsafe.Add(unsafe.Pointer(unsafe.Add(unsafe.Pointer(params), (3*4))), 18)) = int16(int32(((payload).Address).F1))
*(*int16)(unsafe.Add(unsafe.Pointer(unsafe.Add(unsafe.Pointer(params), (3*4))), 20)) = int16(int32(((payload).Address).F2))
*(*int16)(unsafe.Add(unsafe.Pointer(unsafe.Add(unsafe.Pointer(params), (3*4))), 22)) = int16(int32(((payload).Address).F3))
*(*int16)(unsafe.Add(unsafe.Pointer(unsafe.Add(unsafe.Pointer(params), (3*4))), 24)) = int16(int32(((payload).Address).F4))
*(*int16)(unsafe.Add(unsafe.Pointer(unsafe.Add(unsafe.Pointer(params), (3*4))), 26)) = int16(int32(((payload).Address).F5))
*(*int16)(unsafe.Add(unsafe.Pointer(unsafe.Add(unsafe.Pointer(params), (3*4))), 28)) = int16(int32(((payload).Address).F6))
*(*int16)(unsafe.Add(unsafe.Pointer(unsafe.Add(unsafe.Pointer(params), (3*4))), 30)) = int16(int32(((payload).Address).F7))
*(*int32)(unsafe.Add(unsafe.Pointer(unsafe.Add(unsafe.Pointer(params), (3*4))), 32)) = int32((payload).ScopeId)

        

default:
        panic("unreachable")
}

        
default:
        panic("unreachable")
}

wit_async.SubtaskWait(uint32(wasm_import_method_udp_socket_send(uintptr(params), returnArea)))
var result wit_types.Result[wit_types.Unit, ErrorCode]
switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
case 0:
        
        result = wit_types.Ok[wit_types.Unit, ErrorCode](wit_types.Unit{})
case 1:
        
        result = wit_types.Err[wit_types.Unit, ErrorCode](uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 1)))))
default:
        panic("unreachable")
}

return result

}

//go:wasmimport wasi:sockets/types@0.3.0-rc-2025-09-16 [async-lower][method]udp-socket.receive
func wasm_import_method_udp_socket_receive(arg0 int32, arg1 uintptr) int32

func (self *UdpSocket) Receive() wit_types.Result[wit_types.Tuple2[[]uint8, IpSocketAddress], ErrorCode] {
        pinner := &runtime.Pinner{}
defer pinner.Unpin()

        returnArea := uintptr(wit_runtime.Allocate(pinner, (32+3*4), 4))
        
wit_async.SubtaskWait(uint32(wasm_import_method_udp_socket_receive((self).Handle(), returnArea)))
var result wit_types.Result[wit_types.Tuple2[[]uint8, IpSocketAddress], ErrorCode]
switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
case 0:
        value := unsafe.Slice((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2*4))))
var variant IpSocketAddress
switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3*4)))) {
case 0:
        
        variant = MakeIpSocketAddressIpv4(Ipv4SocketAddress{uint16(uint16(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (4+3*4))))), wit_types.Tuple4[uint8, uint8, uint8, uint8]{uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (6+3*4))))), uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (7+3*4))))), uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (8+3*4))))), uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (9+3*4)))))}})

case 1:
        
        variant = MakeIpSocketAddressIpv6(Ipv6SocketAddress{uint16(uint16(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (4+3*4))))), uint32(*(*int32)(unsafe.Add(unsafe.Pointer(returnArea), (8+3*4)))), wit_types.Tuple8[uint16, uint16, uint16, uint16, uint16, uint16, uint16, uint16]{uint16(uint16(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (12+3*4))))), uint16(uint16(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (14+3*4))))), uint16(uint16(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16+3*4))))), uint16(uint16(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (18+3*4))))), uint16(uint16(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (20+3*4))))), uint16(uint16(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (22+3*4))))), uint16(uint16(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (24+3*4))))), uint16(uint16(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (26+3*4)))))}, uint32(*(*int32)(unsafe.Add(unsafe.Pointer(returnArea), (28+3*4))))})

default:
        panic("unreachable")
}

        result = wit_types.Ok[wit_types.Tuple2[[]uint8, IpSocketAddress], ErrorCode](wit_types.Tuple2[[]uint8, IpSocketAddress]{value, variant})
case 1:
        
        result = wit_types.Err[wit_types.Tuple2[[]uint8, IpSocketAddress], ErrorCode](uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4)))))
default:
        panic("unreachable")
}

return result

}

//go:wasmimport wasi:sockets/types@0.3.0-rc-2025-09-16 [method]udp-socket.get-local-address
func wasm_import_method_udp_socket_get_local_address(arg0 int32, arg1 uintptr) 

func (self *UdpSocket) GetLocalAddress() wit_types.Result[IpSocketAddress, ErrorCode] {
        pinner := &runtime.Pinner{}
defer pinner.Unpin()

        returnArea := uintptr(wit_runtime.Allocate(pinner, 36, 4))
        wasm_import_method_udp_socket_get_local_address((self).Handle(), returnArea)
var result wit_types.Result[IpSocketAddress, ErrorCode]
switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
case 0:
        var variant IpSocketAddress
switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))) {
case 0:
        
        variant = MakeIpSocketAddressIpv4(Ipv4SocketAddress{uint16(uint16(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 8)))), wit_types.Tuple4[uint8, uint8, uint8, uint8]{uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 10)))), uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 11)))), uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 12)))), uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 13))))}})

case 1:
        
        variant = MakeIpSocketAddressIpv6(Ipv6SocketAddress{uint16(uint16(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 8)))), uint32(*(*int32)(unsafe.Add(unsafe.Pointer(returnArea), 12))), wit_types.Tuple8[uint16, uint16, uint16, uint16, uint16, uint16, uint16, uint16]{uint16(uint16(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16)))), uint16(uint16(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 18)))), uint16(uint16(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 20)))), uint16(uint16(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 22)))), uint16(uint16(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 24)))), uint16(uint16(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 26)))), uint16(uint16(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 28)))), uint16(uint16(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 30))))}, uint32(*(*int32)(unsafe.Add(unsafe.Pointer(returnArea), 32)))})

default:
        panic("unreachable")
}

        result = wit_types.Ok[IpSocketAddress, ErrorCode](variant)
case 1:
        
        result = wit_types.Err[IpSocketAddress, ErrorCode](uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4)))))
default:
        panic("unreachable")
}
result0 := result;
return result0

}

//go:wasmimport wasi:sockets/types@0.3.0-rc-2025-09-16 [method]udp-socket.get-remote-address
func wasm_import_method_udp_socket_get_remote_address(arg0 int32, arg1 uintptr) 

func (self *UdpSocket) GetRemoteAddress() wit_types.Result[IpSocketAddress, ErrorCode] {
        pinner := &runtime.Pinner{}
defer pinner.Unpin()

        returnArea := uintptr(wit_runtime.Allocate(pinner, 36, 4))
        wasm_import_method_udp_socket_get_remote_address((self).Handle(), returnArea)
var result wit_types.Result[IpSocketAddress, ErrorCode]
switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
case 0:
        var variant IpSocketAddress
switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))) {
case 0:
        
        variant = MakeIpSocketAddressIpv4(Ipv4SocketAddress{uint16(uint16(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 8)))), wit_types.Tuple4[uint8, uint8, uint8, uint8]{uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 10)))), uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 11)))), uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 12)))), uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 13))))}})

case 1:
        
        variant = MakeIpSocketAddressIpv6(Ipv6SocketAddress{uint16(uint16(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 8)))), uint32(*(*int32)(unsafe.Add(unsafe.Pointer(returnArea), 12))), wit_types.Tuple8[uint16, uint16, uint16, uint16, uint16, uint16, uint16, uint16]{uint16(uint16(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16)))), uint16(uint16(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 18)))), uint16(uint16(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 20)))), uint16(uint16(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 22)))), uint16(uint16(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 24)))), uint16(uint16(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 26)))), uint16(uint16(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 28)))), uint16(uint16(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 30))))}, uint32(*(*int32)(unsafe.Add(unsafe.Pointer(returnArea), 32)))})

default:
        panic("unreachable")
}

        result = wit_types.Ok[IpSocketAddress, ErrorCode](variant)
case 1:
        
        result = wit_types.Err[IpSocketAddress, ErrorCode](uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4)))))
default:
        panic("unreachable")
}
result0 := result;
return result0

}

//go:wasmimport wasi:sockets/types@0.3.0-rc-2025-09-16 [method]udp-socket.get-address-family
func wasm_import_method_udp_socket_get_address_family(arg0 int32) int32

func (self *UdpSocket) GetAddressFamily() IpAddressFamily {
        
        
        result := wasm_import_method_udp_socket_get_address_family((self).Handle())
return uint8(result)

}

//go:wasmimport wasi:sockets/types@0.3.0-rc-2025-09-16 [method]udp-socket.get-unicast-hop-limit
func wasm_import_method_udp_socket_get_unicast_hop_limit(arg0 int32, arg1 uintptr) 

func (self *UdpSocket) GetUnicastHopLimit() wit_types.Result[uint8, ErrorCode] {
        pinner := &runtime.Pinner{}
defer pinner.Unpin()

        returnArea := uintptr(wit_runtime.Allocate(pinner, 2, 1))
        wasm_import_method_udp_socket_get_unicast_hop_limit((self).Handle(), returnArea)
var result wit_types.Result[uint8, ErrorCode]
switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
case 0:
        
        result = wit_types.Ok[uint8, ErrorCode](uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 1)))))
case 1:
        
        result = wit_types.Err[uint8, ErrorCode](uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 1)))))
default:
        panic("unreachable")
}
result0 := result;
return result0

}

//go:wasmimport wasi:sockets/types@0.3.0-rc-2025-09-16 [method]udp-socket.set-unicast-hop-limit
func wasm_import_method_udp_socket_set_unicast_hop_limit(arg0 int32, arg1 int32, arg2 uintptr) 

func (self *UdpSocket) SetUnicastHopLimit(value uint8) wit_types.Result[wit_types.Unit, ErrorCode] {
        pinner := &runtime.Pinner{}
defer pinner.Unpin()

        returnArea := uintptr(wit_runtime.Allocate(pinner, 2, 1))
        wasm_import_method_udp_socket_set_unicast_hop_limit((self).Handle(), int32(value), returnArea)
var result wit_types.Result[wit_types.Unit, ErrorCode]
switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
case 0:
        
        result = wit_types.Ok[wit_types.Unit, ErrorCode](wit_types.Unit{})
case 1:
        
        result = wit_types.Err[wit_types.Unit, ErrorCode](uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 1)))))
default:
        panic("unreachable")
}
result0 := result;
return result0

}

//go:wasmimport wasi:sockets/types@0.3.0-rc-2025-09-16 [method]udp-socket.get-receive-buffer-size
func wasm_import_method_udp_socket_get_receive_buffer_size(arg0 int32, arg1 uintptr) 

func (self *UdpSocket) GetReceiveBufferSize() wit_types.Result[uint64, ErrorCode] {
        pinner := &runtime.Pinner{}
defer pinner.Unpin()

        returnArea := uintptr(wit_runtime.Allocate(pinner, 16, 8))
        wasm_import_method_udp_socket_get_receive_buffer_size((self).Handle(), returnArea)
var result wit_types.Result[uint64, ErrorCode]
switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
case 0:
        
        result = wit_types.Ok[uint64, ErrorCode](uint64(*(*int64)(unsafe.Add(unsafe.Pointer(returnArea), 8))))
case 1:
        
        result = wit_types.Err[uint64, ErrorCode](uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 8)))))
default:
        panic("unreachable")
}
result0 := result;
return result0

}

//go:wasmimport wasi:sockets/types@0.3.0-rc-2025-09-16 [method]udp-socket.set-receive-buffer-size
func wasm_import_method_udp_socket_set_receive_buffer_size(arg0 int32, arg1 int64, arg2 uintptr) 

func (self *UdpSocket) SetReceiveBufferSize(value uint64) wit_types.Result[wit_types.Unit, ErrorCode] {
        pinner := &runtime.Pinner{}
defer pinner.Unpin()

        returnArea := uintptr(wit_runtime.Allocate(pinner, 2, 1))
        wasm_import_method_udp_socket_set_receive_buffer_size((self).Handle(), int64(value), returnArea)
var result wit_types.Result[wit_types.Unit, ErrorCode]
switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
case 0:
        
        result = wit_types.Ok[wit_types.Unit, ErrorCode](wit_types.Unit{})
case 1:
        
        result = wit_types.Err[wit_types.Unit, ErrorCode](uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 1)))))
default:
        panic("unreachable")
}
result0 := result;
return result0

}

//go:wasmimport wasi:sockets/types@0.3.0-rc-2025-09-16 [method]udp-socket.get-send-buffer-size
func wasm_import_method_udp_socket_get_send_buffer_size(arg0 int32, arg1 uintptr) 

func (self *UdpSocket) GetSendBufferSize() wit_types.Result[uint64, ErrorCode] {
        pinner := &runtime.Pinner{}
defer pinner.Unpin()

        returnArea := uintptr(wit_runtime.Allocate(pinner, 16, 8))
        wasm_import_method_udp_socket_get_send_buffer_size((self).Handle(), returnArea)
var result wit_types.Result[uint64, ErrorCode]
switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
case 0:
        
        result = wit_types.Ok[uint64, ErrorCode](uint64(*(*int64)(unsafe.Add(unsafe.Pointer(returnArea), 8))))
case 1:
        
        result = wit_types.Err[uint64, ErrorCode](uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 8)))))
default:
        panic("unreachable")
}
result0 := result;
return result0

}

//go:wasmimport wasi:sockets/types@0.3.0-rc-2025-09-16 [method]udp-socket.set-send-buffer-size
func wasm_import_method_udp_socket_set_send_buffer_size(arg0 int32, arg1 int64, arg2 uintptr) 

func (self *UdpSocket) SetSendBufferSize(value uint64) wit_types.Result[wit_types.Unit, ErrorCode] {
        pinner := &runtime.Pinner{}
defer pinner.Unpin()

        returnArea := uintptr(wit_runtime.Allocate(pinner, 2, 1))
        wasm_import_method_udp_socket_set_send_buffer_size((self).Handle(), int64(value), returnArea)
var result wit_types.Result[wit_types.Unit, ErrorCode]
switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
case 0:
        
        result = wit_types.Ok[wit_types.Unit, ErrorCode](wit_types.Unit{})
case 1:
        
        result = wit_types.Err[wit_types.Unit, ErrorCode](uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 1)))))
default:
        panic("unreachable")
}
result0 := result;
return result0

}
