build:
    @# If the wasip1 reactor file isn't present, retrieve it.
    [ -f "wasi_snapshot_preview1.reactor.wasm" ] || curl -OL https://github.com/bytecodealliance/wasmtime/releases/download/v39.0.1/wasi_snapshot_preview1.reactor.wasm

    @# Build the core wasm module.
    GOOS=wasip1 GOARCH=wasm go build -o main.core.wasm -buildmode=c-shared -ldflags=-checklinkname=0 .

    @# Embed the WIT in the core module.
    wasm-tools component embed -w http-trigger --output main.wit.wasm ../../wit main.core.wasm

    @# Create a component from the module, adapting WASI preview1 imports to the component model.
    wasm-tools component new --adapt wasi_snapshot_preview1.reactor.wasm main.wit.wasm --output main.wasm
