// Generated by `wit-bindgen` 0.50.0. DO NOT EDIT!
//
// This code was generated from the following packages:
//     fermyon:spin
//     wasi:io@0.2.0
//     wasi:clocks@0.2.0
//     wasi:random@0.2.0
//     wasi:filesystem@0.2.0
//     wasi:sockets@0.2.0
//     wasi:cli@0.2.0
//     wasi:http@0.2.0
//     wasi:io@0.2.0-rc-2023-10-18
//     wasi:clocks@0.2.0-rc-2023-10-18
//     wasi:random@0.2.0-rc-2023-10-18
//     wasi:filesystem@0.2.0-rc-2023-10-18
//     wasi:sockets@0.2.0-rc-2023-10-18
//     wasi:cli@0.2.0-rc-2023-10-18
//     wasi:http@0.2.0-rc-2023-10-18
//     fermyon:spin@2.0.0
//     wasi:keyvalue@0.2.0-draft2
//     spin:postgres@3.0.0
//     wasi:config@0.2.0-draft-2024-09-27
//     fermyon:spin@3.0.0
//     spin:postgres@4.0.0
//     spin:sqlite@3.0.0
//     wasi:io@0.2.3
//     wasi:clocks@0.2.3
//     wasi:filesystem@0.2.3
//     wasi:sockets@0.2.3
//     wasi:random@0.2.3
//     wasi:cli@0.2.3
//     wasi:http@0.2.3
//     spin:up@3.2.0
//     spin:up@3.4.0
//     wasi:clocks@0.3.0-rc-2025-09-16
//     wasi:random@0.3.0-rc-2025-09-16
//     wasi:filesystem@0.3.0-rc-2025-09-16
//     wasi:sockets@0.3.0-rc-2025-09-16
//     wasi:cli@0.3.0-rc-2025-09-16
//     wasi:http@0.3.0-rc-2025-09-16
//     wasi:io@0.2.6
//     wasi:clocks@0.2.6
//     wasi:filesystem@0.2.6
//     wasi:sockets@0.2.6
//     wasi:random@0.2.6
//     wasi:cli@0.2.6
//     wasi:http@0.2.6
//     spin:up@3.5.0
//     wasi:io@0.2.0-rc-2023-11-10
//     wasi:clocks@0.2.0-rc-2023-11-10
//     wasi:filesystem@0.2.0-rc-2023-11-10
//     wasi:sockets@0.2.0-rc-2023-11-10
//     wasi:random@0.2.0-rc-2023-11-10
//     wasi:cli@0.2.0-rc-2023-11-10
//     wasi:http@0.2.0-rc-2023-11-10

package spin_postgres_4_0_0_postgres

import (
        "github.com/bytecodealliance/wit-bindgen/wit_runtime"
"github.com/bytecodealliance/wit-bindgen/wit_types"
"unsafe"
"runtime"
)


type DbError struct {
        // Stringised version of the error. This is primarily to facilitate migration of older code.
AsText string
Severity string
Code string
Message string
Detail wit_types.Option[string]
// Any error information provided by Postgres and not captured above.
Extras []wit_types.Tuple2[string, string] 
}

const (
// An error occurred but we do not have structured info for it
QueryErrorText uint8 = 0
// Postgres returned a structured database error
QueryErrorDbError uint8 = 1
)

type QueryError struct {
        tag uint8
        value any
}

func (self QueryError) Tag() uint8 {
        return self.tag
}

func (self QueryError) Text() string {
        if self.tag != QueryErrorText {
                panic("tag mismatch")
        }
        return self.value.(string)
}
func (self QueryError) DbError() DbError {
        if self.tag != QueryErrorDbError {
                panic("tag mismatch")
        }
        return self.value.(DbError)
}

func MakeQueryErrorText(value string) QueryError {
        return QueryError{QueryErrorText, value}
}
func MakeQueryErrorDbError(value DbError) QueryError {
        return QueryError{QueryErrorDbError, value}
}



const (
ErrorConnectionFailed uint8 = 0
ErrorBadParameter uint8 = 1
ErrorQueryFailed uint8 = 2
ErrorValueConversionFailed uint8 = 3
ErrorOther uint8 = 4
)

// Errors related to interacting with a database.
type Error struct {
        tag uint8
        value any
}

func (self Error) Tag() uint8 {
        return self.tag
}

func (self Error) ConnectionFailed() string {
        if self.tag != ErrorConnectionFailed {
                panic("tag mismatch")
        }
        return self.value.(string)
}
func (self Error) BadParameter() string {
        if self.tag != ErrorBadParameter {
                panic("tag mismatch")
        }
        return self.value.(string)
}
func (self Error) QueryFailed() QueryError {
        if self.tag != ErrorQueryFailed {
                panic("tag mismatch")
        }
        return self.value.(QueryError)
}
func (self Error) ValueConversionFailed() string {
        if self.tag != ErrorValueConversionFailed {
                panic("tag mismatch")
        }
        return self.value.(string)
}
func (self Error) Other() string {
        if self.tag != ErrorOther {
                panic("tag mismatch")
        }
        return self.value.(string)
}

func MakeErrorConnectionFailed(value string) Error {
        return Error{ErrorConnectionFailed, value}
}
func MakeErrorBadParameter(value string) Error {
        return Error{ErrorBadParameter, value}
}
func MakeErrorQueryFailed(value QueryError) Error {
        return Error{ErrorQueryFailed, value}
}
func MakeErrorValueConversionFailed(value string) Error {
        return Error{ErrorValueConversionFailed, value}
}
func MakeErrorOther(value string) Error {
        return Error{ErrorOther, value}
}



const (
DbDataTypeBoolean uint8 = 0
DbDataTypeInt8 uint8 = 1
DbDataTypeInt16 uint8 = 2
DbDataTypeInt32 uint8 = 3
DbDataTypeInt64 uint8 = 4
DbDataTypeFloating32 uint8 = 5
DbDataTypeFloating64 uint8 = 6
DbDataTypeStr uint8 = 7
DbDataTypeBinary uint8 = 8
DbDataTypeDate uint8 = 9
DbDataTypeTime uint8 = 10
DbDataTypeDatetime uint8 = 11
DbDataTypeTimestamp uint8 = 12
DbDataTypeUuid uint8 = 13
DbDataTypeJsonb uint8 = 14
DbDataTypeDecimal uint8 = 15
DbDataTypeRangeInt32 uint8 = 16
DbDataTypeRangeInt64 uint8 = 17
DbDataTypeRangeDecimal uint8 = 18
DbDataTypeArrayInt32 uint8 = 19
DbDataTypeArrayInt64 uint8 = 20
DbDataTypeArrayDecimal uint8 = 21
DbDataTypeArrayStr uint8 = 22
DbDataTypeInterval uint8 = 23
DbDataTypeOther uint8 = 24
)

// Data types for a database column
type DbDataType struct {
        tag uint8
        value any
}

func (self DbDataType) Tag() uint8 {
        return self.tag
}

func (self DbDataType) Other() string {
        if self.tag != DbDataTypeOther {
                panic("tag mismatch")
        }
        return self.value.(string)
}

func MakeDbDataTypeBoolean() DbDataType {
        return DbDataType{DbDataTypeBoolean, nil}
}
func MakeDbDataTypeInt8() DbDataType {
        return DbDataType{DbDataTypeInt8, nil}
}
func MakeDbDataTypeInt16() DbDataType {
        return DbDataType{DbDataTypeInt16, nil}
}
func MakeDbDataTypeInt32() DbDataType {
        return DbDataType{DbDataTypeInt32, nil}
}
func MakeDbDataTypeInt64() DbDataType {
        return DbDataType{DbDataTypeInt64, nil}
}
func MakeDbDataTypeFloating32() DbDataType {
        return DbDataType{DbDataTypeFloating32, nil}
}
func MakeDbDataTypeFloating64() DbDataType {
        return DbDataType{DbDataTypeFloating64, nil}
}
func MakeDbDataTypeStr() DbDataType {
        return DbDataType{DbDataTypeStr, nil}
}
func MakeDbDataTypeBinary() DbDataType {
        return DbDataType{DbDataTypeBinary, nil}
}
func MakeDbDataTypeDate() DbDataType {
        return DbDataType{DbDataTypeDate, nil}
}
func MakeDbDataTypeTime() DbDataType {
        return DbDataType{DbDataTypeTime, nil}
}
func MakeDbDataTypeDatetime() DbDataType {
        return DbDataType{DbDataTypeDatetime, nil}
}
func MakeDbDataTypeTimestamp() DbDataType {
        return DbDataType{DbDataTypeTimestamp, nil}
}
func MakeDbDataTypeUuid() DbDataType {
        return DbDataType{DbDataTypeUuid, nil}
}
func MakeDbDataTypeJsonb() DbDataType {
        return DbDataType{DbDataTypeJsonb, nil}
}
func MakeDbDataTypeDecimal() DbDataType {
        return DbDataType{DbDataTypeDecimal, nil}
}
func MakeDbDataTypeRangeInt32() DbDataType {
        return DbDataType{DbDataTypeRangeInt32, nil}
}
func MakeDbDataTypeRangeInt64() DbDataType {
        return DbDataType{DbDataTypeRangeInt64, nil}
}
func MakeDbDataTypeRangeDecimal() DbDataType {
        return DbDataType{DbDataTypeRangeDecimal, nil}
}
func MakeDbDataTypeArrayInt32() DbDataType {
        return DbDataType{DbDataTypeArrayInt32, nil}
}
func MakeDbDataTypeArrayInt64() DbDataType {
        return DbDataType{DbDataTypeArrayInt64, nil}
}
func MakeDbDataTypeArrayDecimal() DbDataType {
        return DbDataType{DbDataTypeArrayDecimal, nil}
}
func MakeDbDataTypeArrayStr() DbDataType {
        return DbDataType{DbDataTypeArrayStr, nil}
}
func MakeDbDataTypeInterval() DbDataType {
        return DbDataType{DbDataTypeInterval, nil}
}
func MakeDbDataTypeOther(value string) DbDataType {
        return DbDataType{DbDataTypeOther, value}
}



type Interval struct {
        Micros int64
Days int32
Months int32 
}

// A database column
type Column struct {
        Name string
DataType DbDataType 
}

const (
        RangeBoundKindInclusive uint8 = 0
RangeBoundKindExclusive uint8 = 1
)
// For range types, indicates if each bound is inclusive or exclusive
type RangeBoundKind = uint8

const (
DbValueBoolean uint8 = 0
DbValueInt8 uint8 = 1
DbValueInt16 uint8 = 2
DbValueInt32 uint8 = 3
DbValueInt64 uint8 = 4
DbValueFloating32 uint8 = 5
DbValueFloating64 uint8 = 6
DbValueStr uint8 = 7
DbValueBinary uint8 = 8
DbValueDate uint8 = 9
// (year, month, day)
DbValueTime uint8 = 10
// (hour, minute, second, nanosecond)
// Date-time types are always treated as UTC (without timezone info).
// The instant is represented as a (year, month, day, hour, minute, second, nanosecond) tuple.
DbValueDatetime uint8 = 11
// Unix timestamp (seconds since epoch)
DbValueTimestamp uint8 = 12
DbValueUuid uint8 = 13
DbValueJsonb uint8 = 14
DbValueDecimal uint8 = 15
// I admit defeat. Base 10
DbValueRangeInt32 uint8 = 16
DbValueRangeInt64 uint8 = 17
DbValueRangeDecimal uint8 = 18
DbValueArrayInt32 uint8 = 19
DbValueArrayInt64 uint8 = 20
DbValueArrayDecimal uint8 = 21
DbValueArrayStr uint8 = 22
DbValueInterval uint8 = 23
DbValueDbNull uint8 = 24
DbValueUnsupported uint8 = 25
)

// Database values
type DbValue struct {
        tag uint8
        value any
}

func (self DbValue) Tag() uint8 {
        return self.tag
}

func (self DbValue) Boolean() bool {
        if self.tag != DbValueBoolean {
                panic("tag mismatch")
        }
        return self.value.(bool)
}
func (self DbValue) Int8() int8 {
        if self.tag != DbValueInt8 {
                panic("tag mismatch")
        }
        return self.value.(int8)
}
func (self DbValue) Int16() int16 {
        if self.tag != DbValueInt16 {
                panic("tag mismatch")
        }
        return self.value.(int16)
}
func (self DbValue) Int32() int32 {
        if self.tag != DbValueInt32 {
                panic("tag mismatch")
        }
        return self.value.(int32)
}
func (self DbValue) Int64() int64 {
        if self.tag != DbValueInt64 {
                panic("tag mismatch")
        }
        return self.value.(int64)
}
func (self DbValue) Floating32() float32 {
        if self.tag != DbValueFloating32 {
                panic("tag mismatch")
        }
        return self.value.(float32)
}
func (self DbValue) Floating64() float64 {
        if self.tag != DbValueFloating64 {
                panic("tag mismatch")
        }
        return self.value.(float64)
}
func (self DbValue) Str() string {
        if self.tag != DbValueStr {
                panic("tag mismatch")
        }
        return self.value.(string)
}
func (self DbValue) Binary() []uint8 {
        if self.tag != DbValueBinary {
                panic("tag mismatch")
        }
        return self.value.([]uint8)
}
func (self DbValue) Date() wit_types.Tuple3[int32, uint8, uint8] {
        if self.tag != DbValueDate {
                panic("tag mismatch")
        }
        return self.value.(wit_types.Tuple3[int32, uint8, uint8])
}
func (self DbValue) Time() wit_types.Tuple4[uint8, uint8, uint8, uint32] {
        if self.tag != DbValueTime {
                panic("tag mismatch")
        }
        return self.value.(wit_types.Tuple4[uint8, uint8, uint8, uint32])
}
func (self DbValue) Datetime() wit_types.Tuple7[int32, uint8, uint8, uint8, uint8, uint8, uint32] {
        if self.tag != DbValueDatetime {
                panic("tag mismatch")
        }
        return self.value.(wit_types.Tuple7[int32, uint8, uint8, uint8, uint8, uint8, uint32])
}
func (self DbValue) Timestamp() int64 {
        if self.tag != DbValueTimestamp {
                panic("tag mismatch")
        }
        return self.value.(int64)
}
func (self DbValue) Uuid() string {
        if self.tag != DbValueUuid {
                panic("tag mismatch")
        }
        return self.value.(string)
}
func (self DbValue) Jsonb() []uint8 {
        if self.tag != DbValueJsonb {
                panic("tag mismatch")
        }
        return self.value.([]uint8)
}
func (self DbValue) Decimal() string {
        if self.tag != DbValueDecimal {
                panic("tag mismatch")
        }
        return self.value.(string)
}
func (self DbValue) RangeInt32() wit_types.Tuple2[wit_types.Option[wit_types.Tuple2[int32, RangeBoundKind]], wit_types.Option[wit_types.Tuple2[int32, RangeBoundKind]]] {
        if self.tag != DbValueRangeInt32 {
                panic("tag mismatch")
        }
        return self.value.(wit_types.Tuple2[wit_types.Option[wit_types.Tuple2[int32, RangeBoundKind]], wit_types.Option[wit_types.Tuple2[int32, RangeBoundKind]]])
}
func (self DbValue) RangeInt64() wit_types.Tuple2[wit_types.Option[wit_types.Tuple2[int64, RangeBoundKind]], wit_types.Option[wit_types.Tuple2[int64, RangeBoundKind]]] {
        if self.tag != DbValueRangeInt64 {
                panic("tag mismatch")
        }
        return self.value.(wit_types.Tuple2[wit_types.Option[wit_types.Tuple2[int64, RangeBoundKind]], wit_types.Option[wit_types.Tuple2[int64, RangeBoundKind]]])
}
func (self DbValue) RangeDecimal() wit_types.Tuple2[wit_types.Option[wit_types.Tuple2[string, RangeBoundKind]], wit_types.Option[wit_types.Tuple2[string, RangeBoundKind]]] {
        if self.tag != DbValueRangeDecimal {
                panic("tag mismatch")
        }
        return self.value.(wit_types.Tuple2[wit_types.Option[wit_types.Tuple2[string, RangeBoundKind]], wit_types.Option[wit_types.Tuple2[string, RangeBoundKind]]])
}
func (self DbValue) ArrayInt32() []wit_types.Option[int32] {
        if self.tag != DbValueArrayInt32 {
                panic("tag mismatch")
        }
        return self.value.([]wit_types.Option[int32])
}
func (self DbValue) ArrayInt64() []wit_types.Option[int64] {
        if self.tag != DbValueArrayInt64 {
                panic("tag mismatch")
        }
        return self.value.([]wit_types.Option[int64])
}
func (self DbValue) ArrayDecimal() []wit_types.Option[string] {
        if self.tag != DbValueArrayDecimal {
                panic("tag mismatch")
        }
        return self.value.([]wit_types.Option[string])
}
func (self DbValue) ArrayStr() []wit_types.Option[string] {
        if self.tag != DbValueArrayStr {
                panic("tag mismatch")
        }
        return self.value.([]wit_types.Option[string])
}
func (self DbValue) Interval() Interval {
        if self.tag != DbValueInterval {
                panic("tag mismatch")
        }
        return self.value.(Interval)
}
func (self DbValue) Unsupported() []uint8 {
        if self.tag != DbValueUnsupported {
                panic("tag mismatch")
        }
        return self.value.([]uint8)
}

func MakeDbValueBoolean(value bool) DbValue {
        return DbValue{DbValueBoolean, value}
}
func MakeDbValueInt8(value int8) DbValue {
        return DbValue{DbValueInt8, value}
}
func MakeDbValueInt16(value int16) DbValue {
        return DbValue{DbValueInt16, value}
}
func MakeDbValueInt32(value int32) DbValue {
        return DbValue{DbValueInt32, value}
}
func MakeDbValueInt64(value int64) DbValue {
        return DbValue{DbValueInt64, value}
}
func MakeDbValueFloating32(value float32) DbValue {
        return DbValue{DbValueFloating32, value}
}
func MakeDbValueFloating64(value float64) DbValue {
        return DbValue{DbValueFloating64, value}
}
func MakeDbValueStr(value string) DbValue {
        return DbValue{DbValueStr, value}
}
func MakeDbValueBinary(value []uint8) DbValue {
        return DbValue{DbValueBinary, value}
}
func MakeDbValueDate(value wit_types.Tuple3[int32, uint8, uint8]) DbValue {
        return DbValue{DbValueDate, value}
}
func MakeDbValueTime(value wit_types.Tuple4[uint8, uint8, uint8, uint32]) DbValue {
        return DbValue{DbValueTime, value}
}
func MakeDbValueDatetime(value wit_types.Tuple7[int32, uint8, uint8, uint8, uint8, uint8, uint32]) DbValue {
        return DbValue{DbValueDatetime, value}
}
func MakeDbValueTimestamp(value int64) DbValue {
        return DbValue{DbValueTimestamp, value}
}
func MakeDbValueUuid(value string) DbValue {
        return DbValue{DbValueUuid, value}
}
func MakeDbValueJsonb(value []uint8) DbValue {
        return DbValue{DbValueJsonb, value}
}
func MakeDbValueDecimal(value string) DbValue {
        return DbValue{DbValueDecimal, value}
}
func MakeDbValueRangeInt32(value wit_types.Tuple2[wit_types.Option[wit_types.Tuple2[int32, RangeBoundKind]], wit_types.Option[wit_types.Tuple2[int32, RangeBoundKind]]]) DbValue {
        return DbValue{DbValueRangeInt32, value}
}
func MakeDbValueRangeInt64(value wit_types.Tuple2[wit_types.Option[wit_types.Tuple2[int64, RangeBoundKind]], wit_types.Option[wit_types.Tuple2[int64, RangeBoundKind]]]) DbValue {
        return DbValue{DbValueRangeInt64, value}
}
func MakeDbValueRangeDecimal(value wit_types.Tuple2[wit_types.Option[wit_types.Tuple2[string, RangeBoundKind]], wit_types.Option[wit_types.Tuple2[string, RangeBoundKind]]]) DbValue {
        return DbValue{DbValueRangeDecimal, value}
}
func MakeDbValueArrayInt32(value []wit_types.Option[int32]) DbValue {
        return DbValue{DbValueArrayInt32, value}
}
func MakeDbValueArrayInt64(value []wit_types.Option[int64]) DbValue {
        return DbValue{DbValueArrayInt64, value}
}
func MakeDbValueArrayDecimal(value []wit_types.Option[string]) DbValue {
        return DbValue{DbValueArrayDecimal, value}
}
func MakeDbValueArrayStr(value []wit_types.Option[string]) DbValue {
        return DbValue{DbValueArrayStr, value}
}
func MakeDbValueInterval(value Interval) DbValue {
        return DbValue{DbValueInterval, value}
}
func MakeDbValueDbNull() DbValue {
        return DbValue{DbValueDbNull, nil}
}
func MakeDbValueUnsupported(value []uint8) DbValue {
        return DbValue{DbValueUnsupported, value}
}



const (
ParameterValueBoolean uint8 = 0
ParameterValueInt8 uint8 = 1
ParameterValueInt16 uint8 = 2
ParameterValueInt32 uint8 = 3
ParameterValueInt64 uint8 = 4
ParameterValueFloating32 uint8 = 5
ParameterValueFloating64 uint8 = 6
ParameterValueStr uint8 = 7
ParameterValueBinary uint8 = 8
ParameterValueDate uint8 = 9
// (year, month, day)
ParameterValueTime uint8 = 10
// (hour, minute, second, nanosecond)
// Date-time types are always treated as UTC (without timezone info).
// The instant is represented as a (year, month, day, hour, minute, second, nanosecond) tuple.
ParameterValueDatetime uint8 = 11
// Unix timestamp (seconds since epoch)
ParameterValueTimestamp uint8 = 12
ParameterValueUuid uint8 = 13
ParameterValueJsonb uint8 = 14
ParameterValueDecimal uint8 = 15
// base 10
ParameterValueRangeInt32 uint8 = 16
ParameterValueRangeInt64 uint8 = 17
ParameterValueRangeDecimal uint8 = 18
ParameterValueArrayInt32 uint8 = 19
ParameterValueArrayInt64 uint8 = 20
ParameterValueArrayDecimal uint8 = 21
ParameterValueArrayStr uint8 = 22
ParameterValueInterval uint8 = 23
ParameterValueDbNull uint8 = 24
)

// Values used in parameterized queries
type ParameterValue struct {
        tag uint8
        value any
}

func (self ParameterValue) Tag() uint8 {
        return self.tag
}

func (self ParameterValue) Boolean() bool {
        if self.tag != ParameterValueBoolean {
                panic("tag mismatch")
        }
        return self.value.(bool)
}
func (self ParameterValue) Int8() int8 {
        if self.tag != ParameterValueInt8 {
                panic("tag mismatch")
        }
        return self.value.(int8)
}
func (self ParameterValue) Int16() int16 {
        if self.tag != ParameterValueInt16 {
                panic("tag mismatch")
        }
        return self.value.(int16)
}
func (self ParameterValue) Int32() int32 {
        if self.tag != ParameterValueInt32 {
                panic("tag mismatch")
        }
        return self.value.(int32)
}
func (self ParameterValue) Int64() int64 {
        if self.tag != ParameterValueInt64 {
                panic("tag mismatch")
        }
        return self.value.(int64)
}
func (self ParameterValue) Floating32() float32 {
        if self.tag != ParameterValueFloating32 {
                panic("tag mismatch")
        }
        return self.value.(float32)
}
func (self ParameterValue) Floating64() float64 {
        if self.tag != ParameterValueFloating64 {
                panic("tag mismatch")
        }
        return self.value.(float64)
}
func (self ParameterValue) Str() string {
        if self.tag != ParameterValueStr {
                panic("tag mismatch")
        }
        return self.value.(string)
}
func (self ParameterValue) Binary() []uint8 {
        if self.tag != ParameterValueBinary {
                panic("tag mismatch")
        }
        return self.value.([]uint8)
}
func (self ParameterValue) Date() wit_types.Tuple3[int32, uint8, uint8] {
        if self.tag != ParameterValueDate {
                panic("tag mismatch")
        }
        return self.value.(wit_types.Tuple3[int32, uint8, uint8])
}
func (self ParameterValue) Time() wit_types.Tuple4[uint8, uint8, uint8, uint32] {
        if self.tag != ParameterValueTime {
                panic("tag mismatch")
        }
        return self.value.(wit_types.Tuple4[uint8, uint8, uint8, uint32])
}
func (self ParameterValue) Datetime() wit_types.Tuple7[int32, uint8, uint8, uint8, uint8, uint8, uint32] {
        if self.tag != ParameterValueDatetime {
                panic("tag mismatch")
        }
        return self.value.(wit_types.Tuple7[int32, uint8, uint8, uint8, uint8, uint8, uint32])
}
func (self ParameterValue) Timestamp() int64 {
        if self.tag != ParameterValueTimestamp {
                panic("tag mismatch")
        }
        return self.value.(int64)
}
func (self ParameterValue) Uuid() string {
        if self.tag != ParameterValueUuid {
                panic("tag mismatch")
        }
        return self.value.(string)
}
func (self ParameterValue) Jsonb() []uint8 {
        if self.tag != ParameterValueJsonb {
                panic("tag mismatch")
        }
        return self.value.([]uint8)
}
func (self ParameterValue) Decimal() string {
        if self.tag != ParameterValueDecimal {
                panic("tag mismatch")
        }
        return self.value.(string)
}
func (self ParameterValue) RangeInt32() wit_types.Tuple2[wit_types.Option[wit_types.Tuple2[int32, RangeBoundKind]], wit_types.Option[wit_types.Tuple2[int32, RangeBoundKind]]] {
        if self.tag != ParameterValueRangeInt32 {
                panic("tag mismatch")
        }
        return self.value.(wit_types.Tuple2[wit_types.Option[wit_types.Tuple2[int32, RangeBoundKind]], wit_types.Option[wit_types.Tuple2[int32, RangeBoundKind]]])
}
func (self ParameterValue) RangeInt64() wit_types.Tuple2[wit_types.Option[wit_types.Tuple2[int64, RangeBoundKind]], wit_types.Option[wit_types.Tuple2[int64, RangeBoundKind]]] {
        if self.tag != ParameterValueRangeInt64 {
                panic("tag mismatch")
        }
        return self.value.(wit_types.Tuple2[wit_types.Option[wit_types.Tuple2[int64, RangeBoundKind]], wit_types.Option[wit_types.Tuple2[int64, RangeBoundKind]]])
}
func (self ParameterValue) RangeDecimal() wit_types.Tuple2[wit_types.Option[wit_types.Tuple2[string, RangeBoundKind]], wit_types.Option[wit_types.Tuple2[string, RangeBoundKind]]] {
        if self.tag != ParameterValueRangeDecimal {
                panic("tag mismatch")
        }
        return self.value.(wit_types.Tuple2[wit_types.Option[wit_types.Tuple2[string, RangeBoundKind]], wit_types.Option[wit_types.Tuple2[string, RangeBoundKind]]])
}
func (self ParameterValue) ArrayInt32() []wit_types.Option[int32] {
        if self.tag != ParameterValueArrayInt32 {
                panic("tag mismatch")
        }
        return self.value.([]wit_types.Option[int32])
}
func (self ParameterValue) ArrayInt64() []wit_types.Option[int64] {
        if self.tag != ParameterValueArrayInt64 {
                panic("tag mismatch")
        }
        return self.value.([]wit_types.Option[int64])
}
func (self ParameterValue) ArrayDecimal() []wit_types.Option[string] {
        if self.tag != ParameterValueArrayDecimal {
                panic("tag mismatch")
        }
        return self.value.([]wit_types.Option[string])
}
func (self ParameterValue) ArrayStr() []wit_types.Option[string] {
        if self.tag != ParameterValueArrayStr {
                panic("tag mismatch")
        }
        return self.value.([]wit_types.Option[string])
}
func (self ParameterValue) Interval() Interval {
        if self.tag != ParameterValueInterval {
                panic("tag mismatch")
        }
        return self.value.(Interval)
}

func MakeParameterValueBoolean(value bool) ParameterValue {
        return ParameterValue{ParameterValueBoolean, value}
}
func MakeParameterValueInt8(value int8) ParameterValue {
        return ParameterValue{ParameterValueInt8, value}
}
func MakeParameterValueInt16(value int16) ParameterValue {
        return ParameterValue{ParameterValueInt16, value}
}
func MakeParameterValueInt32(value int32) ParameterValue {
        return ParameterValue{ParameterValueInt32, value}
}
func MakeParameterValueInt64(value int64) ParameterValue {
        return ParameterValue{ParameterValueInt64, value}
}
func MakeParameterValueFloating32(value float32) ParameterValue {
        return ParameterValue{ParameterValueFloating32, value}
}
func MakeParameterValueFloating64(value float64) ParameterValue {
        return ParameterValue{ParameterValueFloating64, value}
}
func MakeParameterValueStr(value string) ParameterValue {
        return ParameterValue{ParameterValueStr, value}
}
func MakeParameterValueBinary(value []uint8) ParameterValue {
        return ParameterValue{ParameterValueBinary, value}
}
func MakeParameterValueDate(value wit_types.Tuple3[int32, uint8, uint8]) ParameterValue {
        return ParameterValue{ParameterValueDate, value}
}
func MakeParameterValueTime(value wit_types.Tuple4[uint8, uint8, uint8, uint32]) ParameterValue {
        return ParameterValue{ParameterValueTime, value}
}
func MakeParameterValueDatetime(value wit_types.Tuple7[int32, uint8, uint8, uint8, uint8, uint8, uint32]) ParameterValue {
        return ParameterValue{ParameterValueDatetime, value}
}
func MakeParameterValueTimestamp(value int64) ParameterValue {
        return ParameterValue{ParameterValueTimestamp, value}
}
func MakeParameterValueUuid(value string) ParameterValue {
        return ParameterValue{ParameterValueUuid, value}
}
func MakeParameterValueJsonb(value []uint8) ParameterValue {
        return ParameterValue{ParameterValueJsonb, value}
}
func MakeParameterValueDecimal(value string) ParameterValue {
        return ParameterValue{ParameterValueDecimal, value}
}
func MakeParameterValueRangeInt32(value wit_types.Tuple2[wit_types.Option[wit_types.Tuple2[int32, RangeBoundKind]], wit_types.Option[wit_types.Tuple2[int32, RangeBoundKind]]]) ParameterValue {
        return ParameterValue{ParameterValueRangeInt32, value}
}
func MakeParameterValueRangeInt64(value wit_types.Tuple2[wit_types.Option[wit_types.Tuple2[int64, RangeBoundKind]], wit_types.Option[wit_types.Tuple2[int64, RangeBoundKind]]]) ParameterValue {
        return ParameterValue{ParameterValueRangeInt64, value}
}
func MakeParameterValueRangeDecimal(value wit_types.Tuple2[wit_types.Option[wit_types.Tuple2[string, RangeBoundKind]], wit_types.Option[wit_types.Tuple2[string, RangeBoundKind]]]) ParameterValue {
        return ParameterValue{ParameterValueRangeDecimal, value}
}
func MakeParameterValueArrayInt32(value []wit_types.Option[int32]) ParameterValue {
        return ParameterValue{ParameterValueArrayInt32, value}
}
func MakeParameterValueArrayInt64(value []wit_types.Option[int64]) ParameterValue {
        return ParameterValue{ParameterValueArrayInt64, value}
}
func MakeParameterValueArrayDecimal(value []wit_types.Option[string]) ParameterValue {
        return ParameterValue{ParameterValueArrayDecimal, value}
}
func MakeParameterValueArrayStr(value []wit_types.Option[string]) ParameterValue {
        return ParameterValue{ParameterValueArrayStr, value}
}
func MakeParameterValueInterval(value Interval) ParameterValue {
        return ParameterValue{ParameterValueInterval, value}
}
func MakeParameterValueDbNull() ParameterValue {
        return ParameterValue{ParameterValueDbNull, nil}
}


// A database row
type Row = []DbValue

// A set of database rows
type RowSet struct {
        Columns []Column
Rows [][]DbValue 
}

//go:wasmimport spin:postgres/postgres@4.0.0 [resource-drop]connection
func resourceDropConnection(handle int32)

// A connection to a postgres database.
type Connection struct {
        handle *wit_runtime.Handle
}

func (self *Connection) TakeHandle() int32 {
        return self.handle.Take()
}

func (self *Connection) SetHandle(handle int32) {
        self.handle.Set(handle)
}

func (self *Connection) Handle() int32 {
        return self.handle.Use()
}

func (self *Connection) Drop() {
	handle := self.handle.TakeOrNil()
	if handle != 0 {
		resourceDropConnection(handle)
	}
}

func ConnectionFromOwnHandle(handleValue int32) *Connection {
        handle := wit_runtime.MakeHandle(handleValue)
        value := &Connection{handle}
        runtime.AddCleanup(value, func(_ int) {
                handleValue := handle.TakeOrNil()
                if handleValue != 0 {
                        resourceDropConnection(handleValue)
                }
        }, 0)
        return value
}

func ConnectionFromBorrowHandle(handleValue int32) *Connection {
	return ConnectionFromOwnHandle(handleValue)
}


//go:wasmimport spin:postgres/postgres@4.0.0 [static]connection.open
func wasm_import_static_connection_open(arg0 uintptr, arg1 uint32, arg2 uintptr) 

func ConnectionOpen(address string) wit_types.Result[*Connection, Error] {
        pinner := &runtime.Pinner{}
defer pinner.Unpin()

        returnArea := uintptr(wit_runtime.Allocate(pinner, (16*4), 4))
        utf8 := unsafe.Pointer(unsafe.StringData(address))
pinner.Pin(utf8)
wasm_import_static_connection_open(uintptr(utf8), uint32(len(address)), returnArea)
var result12 wit_types.Result[*Connection, Error]
switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
case 0:
        
        result12 = wit_types.Ok[*Connection, Error](ConnectionFromOwnHandle(int32(uintptr(*(*int32)(unsafe.Add(unsafe.Pointer(returnArea), 4))))))
case 1:
        var variant11 Error
switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))) {
case 0:
        value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3*4))))

        variant11 = MakeErrorConnectionFailed(value)

case 1:
        value0 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3*4))))

        variant11 = MakeErrorBadParameter(value0)

case 2:
        var variant QueryError
switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2*4)))) {
case 0:
        value1 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (4*4))))

        variant = MakeQueryErrorText(value1)

case 1:
        value2 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (4*4))))
value3 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (5*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (6*4))))
value4 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (7*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (8*4))))
value5 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (9*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (10*4))))
var option wit_types.Option[string]
switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (11*4)))) {
case 0:
        
        option = wit_types.None[string]()
case 1:
        value6 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (12*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (13*4))))

        option = wit_types.Some[string](value6)
default:
        panic("unreachable")
}
result := make([]wit_types.Tuple2[string, string], 0, *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (15*4))))
for index := 0; index < int(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (15*4)))); index++ {
        base := unsafe.Add(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (14*4))))), index * (4*4))
        value7 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)))
value8 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (2*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), (3*4))))

        result = append(result, wit_types.Tuple2[string, string]{value7, value8})        
}


        variant = MakeQueryErrorDbError(DbError{value2, value3, value4, value5, option, result})

default:
        panic("unreachable")
}

        variant11 = MakeErrorQueryFailed(variant)

case 3:
        value9 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3*4))))

        variant11 = MakeErrorValueConversionFailed(value9)

case 4:
        value10 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3*4))))

        variant11 = MakeErrorOther(value10)

default:
        panic("unreachable")
}

        result12 = wit_types.Err[*Connection, Error](variant11)
default:
        panic("unreachable")
}
result13 := result12;
return result13

}

//go:wasmimport spin:postgres/postgres@4.0.0 [method]connection.query
func wasm_import_method_connection_query(arg0 int32, arg1 uintptr, arg2 uint32, arg3 uintptr, arg4 uint32, arg5 uintptr) 

func (self *Connection) Query(statement string, params []ParameterValue) wit_types.Result[RowSet, Error] {
        pinner := &runtime.Pinner{}
defer pinner.Unpin()

        returnArea := uintptr(wit_runtime.Allocate(pinner, (16*4), 4))
        utf8 := unsafe.Pointer(unsafe.StringData(statement))
pinner.Pin(utf8)
slice18 := params
length20 := uint32(len(slice18))
result19 := wit_runtime.Allocate(pinner, uintptr(length20 * (40+4*4)), 8)
for index, element := range slice18 {
        base := unsafe.Add(result19, index * (40+4*4))
        
switch element.Tag() {
case ParameterValueBoolean:
        payload := element.Boolean()
        *(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(0))
var result int32
if payload {
        result = 1
} else {
        result = 0
}
*(*int8)(unsafe.Add(unsafe.Pointer(base), 8)) = int8(result)

        

case ParameterValueInt8:
        payload := element.Int8()
        *(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(1))
*(*int8)(unsafe.Add(unsafe.Pointer(base), 8)) = int8(int32(payload))

        

case ParameterValueInt16:
        payload := element.Int16()
        *(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(2))
*(*int16)(unsafe.Add(unsafe.Pointer(base), 8)) = int16(int32(payload))

        

case ParameterValueInt32:
        payload := element.Int32()
        *(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(3))
*(*int32)(unsafe.Add(unsafe.Pointer(base), 8)) = payload

        

case ParameterValueInt64:
        payload := element.Int64()
        *(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(4))
*(*int64)(unsafe.Add(unsafe.Pointer(base), 8)) = payload

        

case ParameterValueFloating32:
        payload := element.Floating32()
        *(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(5))
*(*float32)(unsafe.Add(unsafe.Pointer(base), 8)) = payload

        

case ParameterValueFloating64:
        payload := element.Floating64()
        *(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(6))
*(*float64)(unsafe.Add(unsafe.Pointer(base), 8)) = payload

        

case ParameterValueStr:
        payload := element.Str()
        *(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(7))
utf80 := unsafe.Pointer(unsafe.StringData(payload))
pinner.Pin(utf80)
*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8+1*4))) = uint32(uint32(len(payload)))
*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8)) = uint32(uintptr(uintptr(utf80)))

        

case ParameterValueBinary:
        payload := element.Binary()
        *(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(8))
data := unsafe.Pointer(unsafe.SliceData(payload))
pinner.Pin(data)
*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8+1*4))) = uint32(uint32(len(payload)))
*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8)) = uint32(uintptr(uintptr(data)))

        

case ParameterValueDate:
        payload := element.Date()
        *(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(9))
*(*int32)(unsafe.Add(unsafe.Pointer(base), 8)) = (payload).F0
*(*int8)(unsafe.Add(unsafe.Pointer(base), 12)) = int8(int32((payload).F1))
*(*int8)(unsafe.Add(unsafe.Pointer(base), 13)) = int8(int32((payload).F2))

        

case ParameterValueTime:
        payload := element.Time()
        *(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(10))
*(*int8)(unsafe.Add(unsafe.Pointer(base), 8)) = int8(int32((payload).F0))
*(*int8)(unsafe.Add(unsafe.Pointer(base), 9)) = int8(int32((payload).F1))
*(*int8)(unsafe.Add(unsafe.Pointer(base), 10)) = int8(int32((payload).F2))
*(*int32)(unsafe.Add(unsafe.Pointer(base), 12)) = int32((payload).F3)

        

case ParameterValueDatetime:
        payload := element.Datetime()
        *(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(11))
*(*int32)(unsafe.Add(unsafe.Pointer(base), 8)) = (payload).F0
*(*int8)(unsafe.Add(unsafe.Pointer(base), 12)) = int8(int32((payload).F1))
*(*int8)(unsafe.Add(unsafe.Pointer(base), 13)) = int8(int32((payload).F2))
*(*int8)(unsafe.Add(unsafe.Pointer(base), 14)) = int8(int32((payload).F3))
*(*int8)(unsafe.Add(unsafe.Pointer(base), 15)) = int8(int32((payload).F4))
*(*int8)(unsafe.Add(unsafe.Pointer(base), 16)) = int8(int32((payload).F5))
*(*int32)(unsafe.Add(unsafe.Pointer(base), 20)) = int32((payload).F6)

        

case ParameterValueTimestamp:
        payload := element.Timestamp()
        *(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(12))
*(*int64)(unsafe.Add(unsafe.Pointer(base), 8)) = payload

        

case ParameterValueUuid:
        payload := element.Uuid()
        *(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(13))
utf81 := unsafe.Pointer(unsafe.StringData(payload))
pinner.Pin(utf81)
*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8+1*4))) = uint32(uint32(len(payload)))
*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8)) = uint32(uintptr(uintptr(utf81)))

        

case ParameterValueJsonb:
        payload := element.Jsonb()
        *(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(14))
data2 := unsafe.Pointer(unsafe.SliceData(payload))
pinner.Pin(data2)
*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8+1*4))) = uint32(uint32(len(payload)))
*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8)) = uint32(uintptr(uintptr(data2)))

        

case ParameterValueDecimal:
        payload := element.Decimal()
        *(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(15))
utf83 := unsafe.Pointer(unsafe.StringData(payload))
pinner.Pin(utf83)
*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8+1*4))) = uint32(uint32(len(payload)))
*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8)) = uint32(uintptr(uintptr(utf83)))

        

case ParameterValueRangeInt32:
        payload := element.RangeInt32()
        *(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(16))

switch (payload).F0.Tag() {
case wit_types.OptionNone:
        *(*int8)(unsafe.Add(unsafe.Pointer(base), 8)) = int8(int32(0))

        
case wit_types.OptionSome:
        payload := (payload).F0.Some()
        *(*int8)(unsafe.Add(unsafe.Pointer(base), 8)) = int8(int32(1))
*(*int32)(unsafe.Add(unsafe.Pointer(base), 12)) = (payload).F0
*(*int8)(unsafe.Add(unsafe.Pointer(base), 16)) = int8(int32((payload).F1))

        
default:
        panic("unreachable")
}

switch (payload).F1.Tag() {
case wit_types.OptionNone:
        *(*int8)(unsafe.Add(unsafe.Pointer(base), 20)) = int8(int32(0))

        
case wit_types.OptionSome:
        payload := (payload).F1.Some()
        *(*int8)(unsafe.Add(unsafe.Pointer(base), 20)) = int8(int32(1))
*(*int32)(unsafe.Add(unsafe.Pointer(base), 24)) = (payload).F0
*(*int8)(unsafe.Add(unsafe.Pointer(base), 28)) = int8(int32((payload).F1))

        
default:
        panic("unreachable")
}

        

case ParameterValueRangeInt64:
        payload := element.RangeInt64()
        *(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(17))

switch (payload).F0.Tag() {
case wit_types.OptionNone:
        *(*int8)(unsafe.Add(unsafe.Pointer(base), 8)) = int8(int32(0))

        
case wit_types.OptionSome:
        payload := (payload).F0.Some()
        *(*int8)(unsafe.Add(unsafe.Pointer(base), 8)) = int8(int32(1))
*(*int64)(unsafe.Add(unsafe.Pointer(base), 16)) = (payload).F0
*(*int8)(unsafe.Add(unsafe.Pointer(base), 24)) = int8(int32((payload).F1))

        
default:
        panic("unreachable")
}

switch (payload).F1.Tag() {
case wit_types.OptionNone:
        *(*int8)(unsafe.Add(unsafe.Pointer(base), 32)) = int8(int32(0))

        
case wit_types.OptionSome:
        payload := (payload).F1.Some()
        *(*int8)(unsafe.Add(unsafe.Pointer(base), 32)) = int8(int32(1))
*(*int64)(unsafe.Add(unsafe.Pointer(base), 40)) = (payload).F0
*(*int8)(unsafe.Add(unsafe.Pointer(base), 48)) = int8(int32((payload).F1))

        
default:
        panic("unreachable")
}

        

case ParameterValueRangeDecimal:
        payload := element.RangeDecimal()
        *(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(18))

switch (payload).F0.Tag() {
case wit_types.OptionNone:
        *(*int8)(unsafe.Add(unsafe.Pointer(base), 8)) = int8(int32(0))

        
case wit_types.OptionSome:
        payload := (payload).F0.Some()
        *(*int8)(unsafe.Add(unsafe.Pointer(base), 8)) = int8(int32(1))
utf84 := unsafe.Pointer(unsafe.StringData((payload).F0))
pinner.Pin(utf84)
*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8+2*4))) = uint32(uint32(len((payload).F0)))
*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8+1*4))) = uint32(uintptr(uintptr(utf84)))
*(*int8)(unsafe.Add(unsafe.Pointer(base), (8+3*4))) = int8(int32((payload).F1))

        
default:
        panic("unreachable")
}

switch (payload).F1.Tag() {
case wit_types.OptionNone:
        *(*int8)(unsafe.Add(unsafe.Pointer(base), (8+4*4))) = int8(int32(0))

        
case wit_types.OptionSome:
        payload := (payload).F1.Some()
        *(*int8)(unsafe.Add(unsafe.Pointer(base), (8+4*4))) = int8(int32(1))
utf85 := unsafe.Pointer(unsafe.StringData((payload).F0))
pinner.Pin(utf85)
*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8+6*4))) = uint32(uint32(len((payload).F0)))
*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8+5*4))) = uint32(uintptr(uintptr(utf85)))
*(*int8)(unsafe.Add(unsafe.Pointer(base), (8+7*4))) = int8(int32((payload).F1))

        
default:
        panic("unreachable")
}

        

case ParameterValueArrayInt32:
        payload := element.ArrayInt32()
        *(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(19))
slice := payload
length := uint32(len(slice))
result6 := wit_runtime.Allocate(pinner, uintptr(length * 8), 4)
for index, element := range slice {
        base := unsafe.Add(result6, index * 8)
        
switch element.Tag() {
case wit_types.OptionNone:
        *(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(0))

        
case wit_types.OptionSome:
        payload := element.Some()
        *(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(1))
*(*int32)(unsafe.Add(unsafe.Pointer(base), 4)) = payload

        
default:
        panic("unreachable")
}

}

*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8+1*4))) = uint32(length)
*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8)) = uint32(uintptr(uintptr(result6)))

        

case ParameterValueArrayInt64:
        payload := element.ArrayInt64()
        *(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(20))
slice7 := payload
length9 := uint32(len(slice7))
result8 := wit_runtime.Allocate(pinner, uintptr(length9 * 16), 8)
for index, element := range slice7 {
        base := unsafe.Add(result8, index * 16)
        
switch element.Tag() {
case wit_types.OptionNone:
        *(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(0))

        
case wit_types.OptionSome:
        payload := element.Some()
        *(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(1))
*(*int64)(unsafe.Add(unsafe.Pointer(base), 8)) = payload

        
default:
        panic("unreachable")
}

}

*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8+1*4))) = uint32(length9)
*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8)) = uint32(uintptr(uintptr(result8)))

        

case ParameterValueArrayDecimal:
        payload := element.ArrayDecimal()
        *(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(21))
slice11 := payload
length13 := uint32(len(slice11))
result12 := wit_runtime.Allocate(pinner, uintptr(length13 * (3*4)), 4)
for index, element := range slice11 {
        base := unsafe.Add(result12, index * (3*4))
        
switch element.Tag() {
case wit_types.OptionNone:
        *(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(0))

        
case wit_types.OptionSome:
        payload := element.Some()
        *(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(1))
utf810 := unsafe.Pointer(unsafe.StringData(payload))
pinner.Pin(utf810)
*(*uint32)(unsafe.Add(unsafe.Pointer(base), (2*4))) = uint32(uint32(len(payload)))
*(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)) = uint32(uintptr(uintptr(utf810)))

        
default:
        panic("unreachable")
}

}

*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8+1*4))) = uint32(length13)
*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8)) = uint32(uintptr(uintptr(result12)))

        

case ParameterValueArrayStr:
        payload := element.ArrayStr()
        *(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(22))
slice15 := payload
length17 := uint32(len(slice15))
result16 := wit_runtime.Allocate(pinner, uintptr(length17 * (3*4)), 4)
for index, element := range slice15 {
        base := unsafe.Add(result16, index * (3*4))
        
switch element.Tag() {
case wit_types.OptionNone:
        *(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(0))

        
case wit_types.OptionSome:
        payload := element.Some()
        *(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(1))
utf814 := unsafe.Pointer(unsafe.StringData(payload))
pinner.Pin(utf814)
*(*uint32)(unsafe.Add(unsafe.Pointer(base), (2*4))) = uint32(uint32(len(payload)))
*(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)) = uint32(uintptr(uintptr(utf814)))

        
default:
        panic("unreachable")
}

}

*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8+1*4))) = uint32(length17)
*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8)) = uint32(uintptr(uintptr(result16)))

        

case ParameterValueInterval:
        payload := element.Interval()
        *(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(23))
*(*int64)(unsafe.Add(unsafe.Pointer(base), 8)) = (payload).Micros
*(*int32)(unsafe.Add(unsafe.Pointer(base), 16)) = (payload).Days
*(*int32)(unsafe.Add(unsafe.Pointer(base), 20)) = (payload).Months

        

case ParameterValueDbNull:
        
        *(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(24))

        

default:
        panic("unreachable")
}

}

wasm_import_method_connection_query((self).Handle(), uintptr(utf8), uint32(len(statement)), uintptr(result19), length20, returnArea)
var result65 wit_types.Result[RowSet, Error]
switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
case 0:
        result22 := make([]Column, 0, *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2*4))))
for index := 0; index < int(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2*4)))); index++ {
        base := unsafe.Add(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4)))), index * (5*4))
        value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)))
var variant DbDataType
switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (2*4)))) {
case 0:
        
        variant = MakeDbDataTypeBoolean()

case 1:
        
        variant = MakeDbDataTypeInt8()

case 2:
        
        variant = MakeDbDataTypeInt16()

case 3:
        
        variant = MakeDbDataTypeInt32()

case 4:
        
        variant = MakeDbDataTypeInt64()

case 5:
        
        variant = MakeDbDataTypeFloating32()

case 6:
        
        variant = MakeDbDataTypeFloating64()

case 7:
        
        variant = MakeDbDataTypeStr()

case 8:
        
        variant = MakeDbDataTypeBinary()

case 9:
        
        variant = MakeDbDataTypeDate()

case 10:
        
        variant = MakeDbDataTypeTime()

case 11:
        
        variant = MakeDbDataTypeDatetime()

case 12:
        
        variant = MakeDbDataTypeTimestamp()

case 13:
        
        variant = MakeDbDataTypeUuid()

case 14:
        
        variant = MakeDbDataTypeJsonb()

case 15:
        
        variant = MakeDbDataTypeDecimal()

case 16:
        
        variant = MakeDbDataTypeRangeInt32()

case 17:
        
        variant = MakeDbDataTypeRangeInt64()

case 18:
        
        variant = MakeDbDataTypeRangeDecimal()

case 19:
        
        variant = MakeDbDataTypeArrayInt32()

case 20:
        
        variant = MakeDbDataTypeArrayInt64()

case 21:
        
        variant = MakeDbDataTypeArrayDecimal()

case 22:
        
        variant = MakeDbDataTypeArrayStr()

case 23:
        
        variant = MakeDbDataTypeInterval()

case 24:
        value21 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (3*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), (4*4))))

        variant = MakeDbDataTypeOther(value21)

default:
        panic("unreachable")
}

        result22 = append(result22, Column{value, variant})        
}

result48 := make([][]DbValue, 0, *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (4*4))))
for index := 0; index < int(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (4*4)))); index++ {
        base := unsafe.Add(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3*4))))), index * (2*4))
        result47 := make([]DbValue, 0, *(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)))
for index := 0; index < int(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 4))); index++ {
        base := unsafe.Add(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0)))), index * (40+4*4))
        var variant46 DbValue
switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0))) {
case 0:
        
        variant46 = MakeDbValueBoolean((uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8))) != 0))

case 1:
        
        variant46 = MakeDbValueInt8(int8(int8(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8)))))

case 2:
        
        variant46 = MakeDbValueInt16(int16(int16(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8)))))

case 3:
        
        variant46 = MakeDbValueInt32(*(*int32)(unsafe.Add(unsafe.Pointer(base), 8)))

case 4:
        
        variant46 = MakeDbValueInt64(*(*int64)(unsafe.Add(unsafe.Pointer(base), 8)))

case 5:
        
        variant46 = MakeDbValueFloating32(*(*float32)(unsafe.Add(unsafe.Pointer(base), 8)))

case 6:
        
        variant46 = MakeDbValueFloating64(*(*float64)(unsafe.Add(unsafe.Pointer(base), 8)))

case 7:
        value23 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), (8+1*4))))

        variant46 = MakeDbValueStr(value23)

case 8:
        value24 := unsafe.Slice((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), (8+1*4))))

        variant46 = MakeDbValueBinary(value24)

case 9:
        
        variant46 = MakeDbValueDate(wit_types.Tuple3[int32, uint8, uint8]{*(*int32)(unsafe.Add(unsafe.Pointer(base), 8)), uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 12)))), uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 13))))})

case 10:
        
        variant46 = MakeDbValueTime(wit_types.Tuple4[uint8, uint8, uint8, uint32]{uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8)))), uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 9)))), uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 10)))), uint32(*(*int32)(unsafe.Add(unsafe.Pointer(base), 12)))})

case 11:
        
        variant46 = MakeDbValueDatetime(wit_types.Tuple7[int32, uint8, uint8, uint8, uint8, uint8, uint32]{*(*int32)(unsafe.Add(unsafe.Pointer(base), 8)), uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 12)))), uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 13)))), uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 14)))), uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 15)))), uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 16)))), uint32(*(*int32)(unsafe.Add(unsafe.Pointer(base), 20)))})

case 12:
        
        variant46 = MakeDbValueTimestamp(*(*int64)(unsafe.Add(unsafe.Pointer(base), 8)))

case 13:
        value25 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), (8+1*4))))

        variant46 = MakeDbValueUuid(value25)

case 14:
        value26 := unsafe.Slice((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), (8+1*4))))

        variant46 = MakeDbValueJsonb(value26)

case 15:
        value27 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), (8+1*4))))

        variant46 = MakeDbValueDecimal(value27)

case 16:
        var option wit_types.Option[wit_types.Tuple2[int32, RangeBoundKind]]
switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8))) {
case 0:
        
        option = wit_types.None[wit_types.Tuple2[int32, RangeBoundKind]]()
case 1:
        
        option = wit_types.Some[wit_types.Tuple2[int32, RangeBoundKind]](wit_types.Tuple2[int32, RangeBoundKind]{*(*int32)(unsafe.Add(unsafe.Pointer(base), 12)), uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 16))))})
default:
        panic("unreachable")
}
var option28 wit_types.Option[wit_types.Tuple2[int32, RangeBoundKind]]
switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 20))) {
case 0:
        
        option28 = wit_types.None[wit_types.Tuple2[int32, RangeBoundKind]]()
case 1:
        
        option28 = wit_types.Some[wit_types.Tuple2[int32, RangeBoundKind]](wit_types.Tuple2[int32, RangeBoundKind]{*(*int32)(unsafe.Add(unsafe.Pointer(base), 24)), uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 28))))})
default:
        panic("unreachable")
}

        variant46 = MakeDbValueRangeInt32(wit_types.Tuple2[wit_types.Option[wit_types.Tuple2[int32, RangeBoundKind]], wit_types.Option[wit_types.Tuple2[int32, RangeBoundKind]]]{option, option28})

case 17:
        var option29 wit_types.Option[wit_types.Tuple2[int64, RangeBoundKind]]
switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8))) {
case 0:
        
        option29 = wit_types.None[wit_types.Tuple2[int64, RangeBoundKind]]()
case 1:
        
        option29 = wit_types.Some[wit_types.Tuple2[int64, RangeBoundKind]](wit_types.Tuple2[int64, RangeBoundKind]{*(*int64)(unsafe.Add(unsafe.Pointer(base), 16)), uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 24))))})
default:
        panic("unreachable")
}
var option30 wit_types.Option[wit_types.Tuple2[int64, RangeBoundKind]]
switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 32))) {
case 0:
        
        option30 = wit_types.None[wit_types.Tuple2[int64, RangeBoundKind]]()
case 1:
        
        option30 = wit_types.Some[wit_types.Tuple2[int64, RangeBoundKind]](wit_types.Tuple2[int64, RangeBoundKind]{*(*int64)(unsafe.Add(unsafe.Pointer(base), 40)), uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 48))))})
default:
        panic("unreachable")
}

        variant46 = MakeDbValueRangeInt64(wit_types.Tuple2[wit_types.Option[wit_types.Tuple2[int64, RangeBoundKind]], wit_types.Option[wit_types.Tuple2[int64, RangeBoundKind]]]{option29, option30})

case 18:
        var option32 wit_types.Option[wit_types.Tuple2[string, RangeBoundKind]]
switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8))) {
case 0:
        
        option32 = wit_types.None[wit_types.Tuple2[string, RangeBoundKind]]()
case 1:
        value31 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8+1*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), (8+2*4))))

        option32 = wit_types.Some[wit_types.Tuple2[string, RangeBoundKind]](wit_types.Tuple2[string, RangeBoundKind]{value31, uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8+3*4)))))})
default:
        panic("unreachable")
}
var option34 wit_types.Option[wit_types.Tuple2[string, RangeBoundKind]]
switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8+4*4)))) {
case 0:
        
        option34 = wit_types.None[wit_types.Tuple2[string, RangeBoundKind]]()
case 1:
        value33 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8+5*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), (8+6*4))))

        option34 = wit_types.Some[wit_types.Tuple2[string, RangeBoundKind]](wit_types.Tuple2[string, RangeBoundKind]{value33, uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8+7*4)))))})
default:
        panic("unreachable")
}

        variant46 = MakeDbValueRangeDecimal(wit_types.Tuple2[wit_types.Option[wit_types.Tuple2[string, RangeBoundKind]], wit_types.Option[wit_types.Tuple2[string, RangeBoundKind]]]{option32, option34})

case 19:
        result36 := make([]wit_types.Option[int32], 0, *(*uint32)(unsafe.Add(unsafe.Pointer(base), (8+1*4))))
for index := 0; index < int(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8+1*4)))); index++ {
        base := unsafe.Add(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8)))), index * 8)
        var option35 wit_types.Option[int32]
switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0))) {
case 0:
        
        option35 = wit_types.None[int32]()
case 1:
        
        option35 = wit_types.Some[int32](*(*int32)(unsafe.Add(unsafe.Pointer(base), 4)))
default:
        panic("unreachable")
}

        result36 = append(result36, option35)        
}


        variant46 = MakeDbValueArrayInt32(result36)

case 20:
        result38 := make([]wit_types.Option[int64], 0, *(*uint32)(unsafe.Add(unsafe.Pointer(base), (8+1*4))))
for index := 0; index < int(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8+1*4)))); index++ {
        base := unsafe.Add(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8)))), index * 16)
        var option37 wit_types.Option[int64]
switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0))) {
case 0:
        
        option37 = wit_types.None[int64]()
case 1:
        
        option37 = wit_types.Some[int64](*(*int64)(unsafe.Add(unsafe.Pointer(base), 8)))
default:
        panic("unreachable")
}

        result38 = append(result38, option37)        
}


        variant46 = MakeDbValueArrayInt64(result38)

case 21:
        result41 := make([]wit_types.Option[string], 0, *(*uint32)(unsafe.Add(unsafe.Pointer(base), (8+1*4))))
for index := 0; index < int(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8+1*4)))); index++ {
        base := unsafe.Add(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8)))), index * (3*4))
        var option40 wit_types.Option[string]
switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0))) {
case 0:
        
        option40 = wit_types.None[string]()
case 1:
        value39 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 4))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), (2*4))))

        option40 = wit_types.Some[string](value39)
default:
        panic("unreachable")
}

        result41 = append(result41, option40)        
}


        variant46 = MakeDbValueArrayDecimal(result41)

case 22:
        result44 := make([]wit_types.Option[string], 0, *(*uint32)(unsafe.Add(unsafe.Pointer(base), (8+1*4))))
for index := 0; index < int(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8+1*4)))); index++ {
        base := unsafe.Add(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8)))), index * (3*4))
        var option43 wit_types.Option[string]
switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0))) {
case 0:
        
        option43 = wit_types.None[string]()
case 1:
        value42 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 4))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), (2*4))))

        option43 = wit_types.Some[string](value42)
default:
        panic("unreachable")
}

        result44 = append(result44, option43)        
}


        variant46 = MakeDbValueArrayStr(result44)

case 23:
        
        variant46 = MakeDbValueInterval(Interval{*(*int64)(unsafe.Add(unsafe.Pointer(base), 8)), *(*int32)(unsafe.Add(unsafe.Pointer(base), 16)), *(*int32)(unsafe.Add(unsafe.Pointer(base), 20))})

case 24:
        
        variant46 = MakeDbValueDbNull()

case 25:
        value45 := unsafe.Slice((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), (8+1*4))))

        variant46 = MakeDbValueUnsupported(value45)

default:
        panic("unreachable")
}

        result47 = append(result47, variant46)        
}


        result48 = append(result48, result47)        
}


        result65 = wit_types.Ok[RowSet, Error](RowSet{result22, result48})
case 1:
        var variant64 Error
switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))) {
case 0:
        value49 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3*4))))

        variant64 = MakeErrorConnectionFailed(value49)

case 1:
        value50 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3*4))))

        variant64 = MakeErrorBadParameter(value50)

case 2:
        var variant61 QueryError
switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2*4)))) {
case 0:
        value51 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (4*4))))

        variant61 = MakeQueryErrorText(value51)

case 1:
        value52 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (4*4))))
value53 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (5*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (6*4))))
value54 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (7*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (8*4))))
value55 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (9*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (10*4))))
var option57 wit_types.Option[string]
switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (11*4)))) {
case 0:
        
        option57 = wit_types.None[string]()
case 1:
        value56 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (12*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (13*4))))

        option57 = wit_types.Some[string](value56)
default:
        panic("unreachable")
}
result60 := make([]wit_types.Tuple2[string, string], 0, *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (15*4))))
for index := 0; index < int(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (15*4)))); index++ {
        base := unsafe.Add(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (14*4))))), index * (4*4))
        value58 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)))
value59 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (2*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), (3*4))))

        result60 = append(result60, wit_types.Tuple2[string, string]{value58, value59})        
}


        variant61 = MakeQueryErrorDbError(DbError{value52, value53, value54, value55, option57, result60})

default:
        panic("unreachable")
}

        variant64 = MakeErrorQueryFailed(variant61)

case 3:
        value62 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3*4))))

        variant64 = MakeErrorValueConversionFailed(value62)

case 4:
        value63 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3*4))))

        variant64 = MakeErrorOther(value63)

default:
        panic("unreachable")
}

        result65 = wit_types.Err[RowSet, Error](variant64)
default:
        panic("unreachable")
}
result66 := result65;
return result66

}

//go:wasmimport spin:postgres/postgres@4.0.0 [method]connection.execute
func wasm_import_method_connection_execute(arg0 int32, arg1 uintptr, arg2 uint32, arg3 uintptr, arg4 uint32, arg5 uintptr) 

func (self *Connection) Execute(statement string, params []ParameterValue) wit_types.Result[uint64, Error] {
        pinner := &runtime.Pinner{}
defer pinner.Unpin()

        returnArea := uintptr(wit_runtime.Allocate(pinner, (16+14*4), 8))
        utf8 := unsafe.Pointer(unsafe.StringData(statement))
pinner.Pin(utf8)
slice18 := params
length20 := uint32(len(slice18))
result19 := wit_runtime.Allocate(pinner, uintptr(length20 * (40+4*4)), 8)
for index, element := range slice18 {
        base := unsafe.Add(result19, index * (40+4*4))
        
switch element.Tag() {
case ParameterValueBoolean:
        payload := element.Boolean()
        *(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(0))
var result int32
if payload {
        result = 1
} else {
        result = 0
}
*(*int8)(unsafe.Add(unsafe.Pointer(base), 8)) = int8(result)

        

case ParameterValueInt8:
        payload := element.Int8()
        *(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(1))
*(*int8)(unsafe.Add(unsafe.Pointer(base), 8)) = int8(int32(payload))

        

case ParameterValueInt16:
        payload := element.Int16()
        *(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(2))
*(*int16)(unsafe.Add(unsafe.Pointer(base), 8)) = int16(int32(payload))

        

case ParameterValueInt32:
        payload := element.Int32()
        *(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(3))
*(*int32)(unsafe.Add(unsafe.Pointer(base), 8)) = payload

        

case ParameterValueInt64:
        payload := element.Int64()
        *(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(4))
*(*int64)(unsafe.Add(unsafe.Pointer(base), 8)) = payload

        

case ParameterValueFloating32:
        payload := element.Floating32()
        *(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(5))
*(*float32)(unsafe.Add(unsafe.Pointer(base), 8)) = payload

        

case ParameterValueFloating64:
        payload := element.Floating64()
        *(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(6))
*(*float64)(unsafe.Add(unsafe.Pointer(base), 8)) = payload

        

case ParameterValueStr:
        payload := element.Str()
        *(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(7))
utf80 := unsafe.Pointer(unsafe.StringData(payload))
pinner.Pin(utf80)
*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8+1*4))) = uint32(uint32(len(payload)))
*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8)) = uint32(uintptr(uintptr(utf80)))

        

case ParameterValueBinary:
        payload := element.Binary()
        *(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(8))
data := unsafe.Pointer(unsafe.SliceData(payload))
pinner.Pin(data)
*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8+1*4))) = uint32(uint32(len(payload)))
*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8)) = uint32(uintptr(uintptr(data)))

        

case ParameterValueDate:
        payload := element.Date()
        *(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(9))
*(*int32)(unsafe.Add(unsafe.Pointer(base), 8)) = (payload).F0
*(*int8)(unsafe.Add(unsafe.Pointer(base), 12)) = int8(int32((payload).F1))
*(*int8)(unsafe.Add(unsafe.Pointer(base), 13)) = int8(int32((payload).F2))

        

case ParameterValueTime:
        payload := element.Time()
        *(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(10))
*(*int8)(unsafe.Add(unsafe.Pointer(base), 8)) = int8(int32((payload).F0))
*(*int8)(unsafe.Add(unsafe.Pointer(base), 9)) = int8(int32((payload).F1))
*(*int8)(unsafe.Add(unsafe.Pointer(base), 10)) = int8(int32((payload).F2))
*(*int32)(unsafe.Add(unsafe.Pointer(base), 12)) = int32((payload).F3)

        

case ParameterValueDatetime:
        payload := element.Datetime()
        *(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(11))
*(*int32)(unsafe.Add(unsafe.Pointer(base), 8)) = (payload).F0
*(*int8)(unsafe.Add(unsafe.Pointer(base), 12)) = int8(int32((payload).F1))
*(*int8)(unsafe.Add(unsafe.Pointer(base), 13)) = int8(int32((payload).F2))
*(*int8)(unsafe.Add(unsafe.Pointer(base), 14)) = int8(int32((payload).F3))
*(*int8)(unsafe.Add(unsafe.Pointer(base), 15)) = int8(int32((payload).F4))
*(*int8)(unsafe.Add(unsafe.Pointer(base), 16)) = int8(int32((payload).F5))
*(*int32)(unsafe.Add(unsafe.Pointer(base), 20)) = int32((payload).F6)

        

case ParameterValueTimestamp:
        payload := element.Timestamp()
        *(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(12))
*(*int64)(unsafe.Add(unsafe.Pointer(base), 8)) = payload

        

case ParameterValueUuid:
        payload := element.Uuid()
        *(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(13))
utf81 := unsafe.Pointer(unsafe.StringData(payload))
pinner.Pin(utf81)
*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8+1*4))) = uint32(uint32(len(payload)))
*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8)) = uint32(uintptr(uintptr(utf81)))

        

case ParameterValueJsonb:
        payload := element.Jsonb()
        *(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(14))
data2 := unsafe.Pointer(unsafe.SliceData(payload))
pinner.Pin(data2)
*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8+1*4))) = uint32(uint32(len(payload)))
*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8)) = uint32(uintptr(uintptr(data2)))

        

case ParameterValueDecimal:
        payload := element.Decimal()
        *(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(15))
utf83 := unsafe.Pointer(unsafe.StringData(payload))
pinner.Pin(utf83)
*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8+1*4))) = uint32(uint32(len(payload)))
*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8)) = uint32(uintptr(uintptr(utf83)))

        

case ParameterValueRangeInt32:
        payload := element.RangeInt32()
        *(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(16))

switch (payload).F0.Tag() {
case wit_types.OptionNone:
        *(*int8)(unsafe.Add(unsafe.Pointer(base), 8)) = int8(int32(0))

        
case wit_types.OptionSome:
        payload := (payload).F0.Some()
        *(*int8)(unsafe.Add(unsafe.Pointer(base), 8)) = int8(int32(1))
*(*int32)(unsafe.Add(unsafe.Pointer(base), 12)) = (payload).F0
*(*int8)(unsafe.Add(unsafe.Pointer(base), 16)) = int8(int32((payload).F1))

        
default:
        panic("unreachable")
}

switch (payload).F1.Tag() {
case wit_types.OptionNone:
        *(*int8)(unsafe.Add(unsafe.Pointer(base), 20)) = int8(int32(0))

        
case wit_types.OptionSome:
        payload := (payload).F1.Some()
        *(*int8)(unsafe.Add(unsafe.Pointer(base), 20)) = int8(int32(1))
*(*int32)(unsafe.Add(unsafe.Pointer(base), 24)) = (payload).F0
*(*int8)(unsafe.Add(unsafe.Pointer(base), 28)) = int8(int32((payload).F1))

        
default:
        panic("unreachable")
}

        

case ParameterValueRangeInt64:
        payload := element.RangeInt64()
        *(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(17))

switch (payload).F0.Tag() {
case wit_types.OptionNone:
        *(*int8)(unsafe.Add(unsafe.Pointer(base), 8)) = int8(int32(0))

        
case wit_types.OptionSome:
        payload := (payload).F0.Some()
        *(*int8)(unsafe.Add(unsafe.Pointer(base), 8)) = int8(int32(1))
*(*int64)(unsafe.Add(unsafe.Pointer(base), 16)) = (payload).F0
*(*int8)(unsafe.Add(unsafe.Pointer(base), 24)) = int8(int32((payload).F1))

        
default:
        panic("unreachable")
}

switch (payload).F1.Tag() {
case wit_types.OptionNone:
        *(*int8)(unsafe.Add(unsafe.Pointer(base), 32)) = int8(int32(0))

        
case wit_types.OptionSome:
        payload := (payload).F1.Some()
        *(*int8)(unsafe.Add(unsafe.Pointer(base), 32)) = int8(int32(1))
*(*int64)(unsafe.Add(unsafe.Pointer(base), 40)) = (payload).F0
*(*int8)(unsafe.Add(unsafe.Pointer(base), 48)) = int8(int32((payload).F1))

        
default:
        panic("unreachable")
}

        

case ParameterValueRangeDecimal:
        payload := element.RangeDecimal()
        *(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(18))

switch (payload).F0.Tag() {
case wit_types.OptionNone:
        *(*int8)(unsafe.Add(unsafe.Pointer(base), 8)) = int8(int32(0))

        
case wit_types.OptionSome:
        payload := (payload).F0.Some()
        *(*int8)(unsafe.Add(unsafe.Pointer(base), 8)) = int8(int32(1))
utf84 := unsafe.Pointer(unsafe.StringData((payload).F0))
pinner.Pin(utf84)
*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8+2*4))) = uint32(uint32(len((payload).F0)))
*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8+1*4))) = uint32(uintptr(uintptr(utf84)))
*(*int8)(unsafe.Add(unsafe.Pointer(base), (8+3*4))) = int8(int32((payload).F1))

        
default:
        panic("unreachable")
}

switch (payload).F1.Tag() {
case wit_types.OptionNone:
        *(*int8)(unsafe.Add(unsafe.Pointer(base), (8+4*4))) = int8(int32(0))

        
case wit_types.OptionSome:
        payload := (payload).F1.Some()
        *(*int8)(unsafe.Add(unsafe.Pointer(base), (8+4*4))) = int8(int32(1))
utf85 := unsafe.Pointer(unsafe.StringData((payload).F0))
pinner.Pin(utf85)
*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8+6*4))) = uint32(uint32(len((payload).F0)))
*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8+5*4))) = uint32(uintptr(uintptr(utf85)))
*(*int8)(unsafe.Add(unsafe.Pointer(base), (8+7*4))) = int8(int32((payload).F1))

        
default:
        panic("unreachable")
}

        

case ParameterValueArrayInt32:
        payload := element.ArrayInt32()
        *(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(19))
slice := payload
length := uint32(len(slice))
result6 := wit_runtime.Allocate(pinner, uintptr(length * 8), 4)
for index, element := range slice {
        base := unsafe.Add(result6, index * 8)
        
switch element.Tag() {
case wit_types.OptionNone:
        *(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(0))

        
case wit_types.OptionSome:
        payload := element.Some()
        *(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(1))
*(*int32)(unsafe.Add(unsafe.Pointer(base), 4)) = payload

        
default:
        panic("unreachable")
}

}

*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8+1*4))) = uint32(length)
*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8)) = uint32(uintptr(uintptr(result6)))

        

case ParameterValueArrayInt64:
        payload := element.ArrayInt64()
        *(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(20))
slice7 := payload
length9 := uint32(len(slice7))
result8 := wit_runtime.Allocate(pinner, uintptr(length9 * 16), 8)
for index, element := range slice7 {
        base := unsafe.Add(result8, index * 16)
        
switch element.Tag() {
case wit_types.OptionNone:
        *(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(0))

        
case wit_types.OptionSome:
        payload := element.Some()
        *(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(1))
*(*int64)(unsafe.Add(unsafe.Pointer(base), 8)) = payload

        
default:
        panic("unreachable")
}

}

*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8+1*4))) = uint32(length9)
*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8)) = uint32(uintptr(uintptr(result8)))

        

case ParameterValueArrayDecimal:
        payload := element.ArrayDecimal()
        *(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(21))
slice11 := payload
length13 := uint32(len(slice11))
result12 := wit_runtime.Allocate(pinner, uintptr(length13 * (3*4)), 4)
for index, element := range slice11 {
        base := unsafe.Add(result12, index * (3*4))
        
switch element.Tag() {
case wit_types.OptionNone:
        *(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(0))

        
case wit_types.OptionSome:
        payload := element.Some()
        *(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(1))
utf810 := unsafe.Pointer(unsafe.StringData(payload))
pinner.Pin(utf810)
*(*uint32)(unsafe.Add(unsafe.Pointer(base), (2*4))) = uint32(uint32(len(payload)))
*(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)) = uint32(uintptr(uintptr(utf810)))

        
default:
        panic("unreachable")
}

}

*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8+1*4))) = uint32(length13)
*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8)) = uint32(uintptr(uintptr(result12)))

        

case ParameterValueArrayStr:
        payload := element.ArrayStr()
        *(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(22))
slice15 := payload
length17 := uint32(len(slice15))
result16 := wit_runtime.Allocate(pinner, uintptr(length17 * (3*4)), 4)
for index, element := range slice15 {
        base := unsafe.Add(result16, index * (3*4))
        
switch element.Tag() {
case wit_types.OptionNone:
        *(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(0))

        
case wit_types.OptionSome:
        payload := element.Some()
        *(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(1))
utf814 := unsafe.Pointer(unsafe.StringData(payload))
pinner.Pin(utf814)
*(*uint32)(unsafe.Add(unsafe.Pointer(base), (2*4))) = uint32(uint32(len(payload)))
*(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)) = uint32(uintptr(uintptr(utf814)))

        
default:
        panic("unreachable")
}

}

*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8+1*4))) = uint32(length17)
*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8)) = uint32(uintptr(uintptr(result16)))

        

case ParameterValueInterval:
        payload := element.Interval()
        *(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(23))
*(*int64)(unsafe.Add(unsafe.Pointer(base), 8)) = (payload).Micros
*(*int32)(unsafe.Add(unsafe.Pointer(base), 16)) = (payload).Days
*(*int32)(unsafe.Add(unsafe.Pointer(base), 20)) = (payload).Months

        

case ParameterValueDbNull:
        
        *(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(24))

        

default:
        panic("unreachable")
}

}

wasm_import_method_connection_execute((self).Handle(), uintptr(utf8), uint32(len(statement)), uintptr(result19), length20, returnArea)
var result34 wit_types.Result[uint64, Error]
switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
case 0:
        
        result34 = wit_types.Ok[uint64, Error](uint64(*(*int64)(unsafe.Add(unsafe.Pointer(returnArea), 8))))
case 1:
        var variant33 Error
switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 8))) {
case 0:
        value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (8+1*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (8+2*4))))

        variant33 = MakeErrorConnectionFailed(value)

case 1:
        value21 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (8+1*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (8+2*4))))

        variant33 = MakeErrorBadParameter(value21)

case 2:
        var variant QueryError
switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (8+1*4)))) {
case 0:
        value22 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (8+2*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (8+3*4))))

        variant = MakeQueryErrorText(value22)

case 1:
        value23 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (8+2*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (8+3*4))))
value24 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (8+4*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (8+5*4))))
value25 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (8+6*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (8+7*4))))
value26 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (8+8*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (8+9*4))))
var option wit_types.Option[string]
switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (8+10*4)))) {
case 0:
        
        option = wit_types.None[string]()
case 1:
        value27 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (8+11*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (8+12*4))))

        option = wit_types.Some[string](value27)
default:
        panic("unreachable")
}
result30 := make([]wit_types.Tuple2[string, string], 0, *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (8+14*4))))
for index := 0; index < int(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (8+14*4)))); index++ {
        base := unsafe.Add(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (8+13*4))))), index * (4*4))
        value28 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)))
value29 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (2*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), (3*4))))

        result30 = append(result30, wit_types.Tuple2[string, string]{value28, value29})        
}


        variant = MakeQueryErrorDbError(DbError{value23, value24, value25, value26, option, result30})

default:
        panic("unreachable")
}

        variant33 = MakeErrorQueryFailed(variant)

case 3:
        value31 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (8+1*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (8+2*4))))

        variant33 = MakeErrorValueConversionFailed(value31)

case 4:
        value32 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (8+1*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (8+2*4))))

        variant33 = MakeErrorOther(value32)

default:
        panic("unreachable")
}

        result34 = wit_types.Err[uint64, Error](variant33)
default:
        panic("unreachable")
}
result35 := result34;
return result35

}
