// Generated by `wit-bindgen` 0.50.0. DO NOT EDIT!
//
// This code was generated from the following packages:
//     fermyon:spin
//     wasi:io@0.2.0
//     wasi:clocks@0.2.0
//     wasi:random@0.2.0
//     wasi:filesystem@0.2.0
//     wasi:sockets@0.2.0
//     wasi:cli@0.2.0
//     wasi:http@0.2.0
//     wasi:io@0.2.0-rc-2023-10-18
//     wasi:clocks@0.2.0-rc-2023-10-18
//     wasi:random@0.2.0-rc-2023-10-18
//     wasi:filesystem@0.2.0-rc-2023-10-18
//     wasi:sockets@0.2.0-rc-2023-10-18
//     wasi:cli@0.2.0-rc-2023-10-18
//     wasi:http@0.2.0-rc-2023-10-18
//     fermyon:spin@2.0.0
//     wasi:keyvalue@0.2.0-draft2
//     spin:postgres@3.0.0
//     wasi:config@0.2.0-draft-2024-09-27
//     fermyon:spin@3.0.0
//     spin:postgres@4.0.0
//     spin:sqlite@3.0.0
//     wasi:io@0.2.3
//     wasi:clocks@0.2.3
//     wasi:filesystem@0.2.3
//     wasi:sockets@0.2.3
//     wasi:random@0.2.3
//     wasi:cli@0.2.3
//     wasi:http@0.2.3
//     spin:up@3.2.0
//     spin:up@3.4.0
//     wasi:clocks@0.3.0-rc-2025-09-16
//     wasi:random@0.3.0-rc-2025-09-16
//     wasi:filesystem@0.3.0-rc-2025-09-16
//     wasi:sockets@0.3.0-rc-2025-09-16
//     wasi:cli@0.3.0-rc-2025-09-16
//     wasi:http@0.3.0-rc-2025-09-16
//     wasi:io@0.2.6
//     wasi:clocks@0.2.6
//     wasi:filesystem@0.2.6
//     wasi:sockets@0.2.6
//     wasi:random@0.2.6
//     wasi:cli@0.2.6
//     wasi:http@0.2.6
//     spin:up@3.5.0
//     wasi:io@0.2.0-rc-2023-11-10
//     wasi:clocks@0.2.0-rc-2023-11-10
//     wasi:filesystem@0.2.0-rc-2023-11-10
//     wasi:sockets@0.2.0-rc-2023-11-10
//     wasi:random@0.2.0-rc-2023-11-10
//     wasi:cli@0.2.0-rc-2023-11-10
//     wasi:http@0.2.0-rc-2023-11-10

package wasi_sockets_0_3_0_rc_2025_09_16_ip_name_lookup

import (
	"runtime"
	"unsafe"

	"github.com/bytecodealliance/wit-bindgen/wit_async"
	"github.com/bytecodealliance/wit-bindgen/wit_runtime"
	"github.com/bytecodealliance/wit-bindgen/wit_types"
	"github.com/spinframework/spin-go-sdk/v4/wit_component/wasi_sockets_0_3_0_rc_2025_09_16_types"
)

type IpAddress = wasi_sockets_0_3_0_rc_2025_09_16_types.IpAddress

const (
	// Unknown error
	ErrorCodeUnknown uint8 = 0
	// Access denied.
	//
	// POSIX equivalent: EACCES, EPERM
	ErrorCodeAccessDenied uint8 = 1
	// `name` is a syntactically invalid domain name or IP address.
	//
	// POSIX equivalent: EINVAL
	ErrorCodeInvalidArgument uint8 = 2
	// Name does not exist or has no suitable associated IP addresses.
	//
	// POSIX equivalent: EAI_NONAME, EAI_NODATA, EAI_ADDRFAMILY
	ErrorCodeNameUnresolvable uint8 = 3
	// A temporary failure in name resolution occurred.
	//
	// POSIX equivalent: EAI_AGAIN
	ErrorCodeTemporaryResolverFailure uint8 = 4
	// A permanent failure in name resolution occurred.
	//
	// POSIX equivalent: EAI_FAIL
	ErrorCodePermanentResolverFailure uint8 = 5
)

// Lookup error codes.
type ErrorCode = uint8

//go:wasmimport wasi:sockets/ip-name-lookup@0.3.0-rc-2025-09-16 [async-lower]resolve-addresses
func wasm_import_resolve_addresses(arg0 uintptr, arg1 uint32, arg2 uintptr) int32

func ResolveAddresses(name string) wit_types.Result[[]wasi_sockets_0_3_0_rc_2025_09_16_types.IpAddress, ErrorCode] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(wit_runtime.Allocate(pinner, (3 * 4), 4))
	utf8 := unsafe.Pointer(unsafe.StringData(name))
	pinner.Pin(utf8)

	wit_async.SubtaskWait(uint32(wasm_import_resolve_addresses(uintptr(utf8), uint32(len(name)), returnArea)))
	var result0 wit_types.Result[[]wasi_sockets_0_3_0_rc_2025_09_16_types.IpAddress, ErrorCode]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:
		result := make([]wasi_sockets_0_3_0_rc_2025_09_16_types.IpAddress, 0, *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4))))
		for index := 0; index < int(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))); index++ {
			base := unsafe.Add(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4)))), index*18)
			var variant wasi_sockets_0_3_0_rc_2025_09_16_types.IpAddress
			switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0))) {
			case 0:

				variant = wasi_sockets_0_3_0_rc_2025_09_16_types.MakeIpAddressIpv4(wit_types.Tuple4[uint8, uint8, uint8, uint8]{uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 2)))), uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 3)))), uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)))), uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 5))))})

			case 1:

				variant = wasi_sockets_0_3_0_rc_2025_09_16_types.MakeIpAddressIpv6(wit_types.Tuple8[uint16, uint16, uint16, uint16, uint16, uint16, uint16, uint16]{uint16(uint16(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 2)))), uint16(uint16(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)))), uint16(uint16(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 6)))), uint16(uint16(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8)))), uint16(uint16(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 10)))), uint16(uint16(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 12)))), uint16(uint16(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 14)))), uint16(uint16(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 16))))})

			default:
				panic("unreachable")
			}

			result = append(result, variant)
		}

		result0 = wit_types.Ok[[]wasi_sockets_0_3_0_rc_2025_09_16_types.IpAddress, ErrorCode](result)
	case 1:

		result0 = wit_types.Err[[]wasi_sockets_0_3_0_rc_2025_09_16_types.IpAddress, ErrorCode](uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4)))))
	default:
		panic("unreachable")
	}

	return result0

}
