// Generated by `wit-bindgen` 0.50.0. DO NOT EDIT!
//
// This code was generated from the following packages:
//     fermyon:spin
//     wasi:io@0.2.0
//     wasi:clocks@0.2.0
//     wasi:random@0.2.0
//     wasi:filesystem@0.2.0
//     wasi:sockets@0.2.0
//     wasi:cli@0.2.0
//     wasi:http@0.2.0
//     wasi:io@0.2.0-rc-2023-10-18
//     wasi:clocks@0.2.0-rc-2023-10-18
//     wasi:random@0.2.0-rc-2023-10-18
//     wasi:filesystem@0.2.0-rc-2023-10-18
//     wasi:sockets@0.2.0-rc-2023-10-18
//     wasi:cli@0.2.0-rc-2023-10-18
//     wasi:http@0.2.0-rc-2023-10-18
//     fermyon:spin@2.0.0
//     wasi:keyvalue@0.2.0-draft2
//     spin:postgres@3.0.0
//     wasi:config@0.2.0-draft-2024-09-27
//     fermyon:spin@3.0.0
//     spin:postgres@4.0.0
//     spin:sqlite@3.0.0
//     wasi:io@0.2.3
//     wasi:clocks@0.2.3
//     wasi:filesystem@0.2.3
//     wasi:sockets@0.2.3
//     wasi:random@0.2.3
//     wasi:cli@0.2.3
//     wasi:http@0.2.3
//     spin:up@3.2.0
//     spin:up@3.4.0
//     wasi:clocks@0.3.0-rc-2025-09-16
//     wasi:random@0.3.0-rc-2025-09-16
//     wasi:filesystem@0.3.0-rc-2025-09-16
//     wasi:sockets@0.3.0-rc-2025-09-16
//     wasi:cli@0.3.0-rc-2025-09-16
//     wasi:http@0.3.0-rc-2025-09-16
//     wasi:io@0.2.6
//     wasi:clocks@0.2.6
//     wasi:filesystem@0.2.6
//     wasi:sockets@0.2.6
//     wasi:random@0.2.6
//     wasi:cli@0.2.6
//     wasi:http@0.2.6
//     spin:up@3.5.0
//     wasi:io@0.2.0-rc-2023-11-10
//     wasi:clocks@0.2.0-rc-2023-11-10
//     wasi:filesystem@0.2.0-rc-2023-11-10
//     wasi:sockets@0.2.0-rc-2023-11-10
//     wasi:random@0.2.0-rc-2023-11-10
//     wasi:cli@0.2.0-rc-2023-11-10
//     wasi:http@0.2.0-rc-2023-11-10

package wasi_cli_0_2_6_stderr

import (
	"github.com/spinframework/spin-go-sdk/v4/wit_component/wasi_io_0_2_6_streams"
)

type OutputStream = wasi_io_0_2_6_streams.OutputStream

//go:wasmimport wasi:cli/stderr@0.2.6 get-stderr
func wasm_import_get_stderr() int32

func GetStderr() *wasi_io_0_2_6_streams.OutputStream {

	result := wasm_import_get_stderr()
	return wasi_io_0_2_6_streams.OutputStreamFromOwnHandle(int32(uintptr(result)))

}
