// Generated by `wit-bindgen` 0.50.0. DO NOT EDIT!
package wasi_cli_0_2_0_terminal_stdout

import (
	"runtime"
	"unsafe"

	"github.com/spinframework/spin-go-sdk/v3/wit_component/wasi_cli_0_2_0_terminal_output"
	"github.com/spinframework/spin-go-sdk/v3/wit_component/wit_runtime"
	"github.com/spinframework/spin-go-sdk/v3/wit_component/wit_types"
)

type TerminalOutput = wasi_cli_0_2_0_terminal_output.TerminalOutput

//go:wasmimport wasi:cli/terminal-stdout@0.2.0 get-terminal-stdout
func wasm_import_get_terminal_stdout(arg0 uintptr)

func GetTerminalStdout() wit_types.Option[*wasi_cli_0_2_0_terminal_output.TerminalOutput] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(wit_runtime.Allocate(pinner, 8, 4))
	wasm_import_get_terminal_stdout(returnArea)
	var option wit_types.Option[*wasi_cli_0_2_0_terminal_output.TerminalOutput]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		option = wit_types.None[*wasi_cli_0_2_0_terminal_output.TerminalOutput]()
	case 1:

		option = wit_types.Some[*wasi_cli_0_2_0_terminal_output.TerminalOutput](wasi_cli_0_2_0_terminal_output.TerminalOutputFromOwnHandle(int32(uintptr(*(*int32)(unsafe.Add(unsafe.Pointer(returnArea), 4))))))
	default:
		panic("unreachable")
	}
	result := option
	return result

}
