name: Run Integration tests
on:
  pull_request:
    branches:
      - wasip2

  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Setup componentize-go
        run: |
          git clone https://github.com/asteurer/componentize-go.git
          cargo install --path ./componentize-go

      - name: Setup Spin
        uses: fermyon/actions/spin/setup@v1
        with:
          version: "v3.5.1"

      - name: Run wasip2 integration tests
        run: make test-integration-wasip2

